---
sidebar: sidebar 
permalink: modern-apps/fpd-ai-dl-design.html 
keywords: cisco, flexpod, ai, ml, data, center, ucs, nvidia 
summary: Dieses Dokument enthält Design-Details zur Integration der Cisco UCS C480 ML M5 Plattform in die FlexPod Datacenter-Lösung. So wird ein einheitlicher Ansatz für die Bereitstellung von KI- und ML-Funktionen in der konvergenten Infrastruktur bereitgestellt. 
---
= FlexPod Datacenter for Combined AI and ML with Cisco UCS 480 ML for Deep Learning – Design
:allow-uri-read: 


Haseeb Niazi, Cisco Arvind Ramakrishnan, NetApp

Dieses Dokument enthält Design-Details zur Integration der Cisco UCS C480 ML M5 Plattform in die FlexPod Datacenter-Lösung. So wird ein einheitlicher Ansatz für die Bereitstellung von KI- und ML-Funktionen in der konvergenten Infrastruktur bereitgestellt. Da Kunden Server, die KI- und ML-Funktionen mit vertrauten Tools kombinieren, die sie zur Administration herkömmlicher FlexPod-Systeme verwenden, managen, werden sowohl der Administrations-Overhead als auch die Kosten für die Implementierung einer Deep-Learning-Plattform erheblich gesenkt. Das in diesem CVD präsentierte Design umfasst auch andere Cisco UCS Plattformen, wie einen C220 M5 Server mit zwei NVIDIA T4 GPUs und einen C240 M5 Server mit zwei NVIDIA V100 32-GB-PCIe-Karten als zusätzliche Optionen für gleichzeitige KI- und ML-Workloads.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_c480m5l_aiml_design.html["FlexPod Datacenter for Combined AI and ML with Cisco UCS 480 ML for Deep Learning – Design"^]
