---
sidebar: sidebar 
permalink: express/express-c-series-aff220-deploy_netapp_aff_storage_deployment_procedure_@part_2@.html 
keywords: san, map, boot, storage, setup, aff, deployment, procedure, igroups 
summary: Zum Erstellen von Initiatorgruppen benötigen Sie die iSCSI-Initiator-IQNs und müssen die folgenden Schritte ausführen. 
---
= NetApp Verfahren zur Implementierung von AFF-Storage (Teil 2)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Einrichtung von ONTAP SAN Boot Storage



=== Erstellen von iSCSI-Initiatorgruppen

Um Initiatorgruppen zu erstellen, führen Sie den folgenden Schritt aus:

Für diesen Schritt benötigen Sie die iSCSI-Initiator-IQNs aus der Serverkonfiguration.

. Führen Sie über die SSH-Verbindung des Cluster-Management-Node die folgenden Befehle aus. Um die drei in diesem Schritt erstellten Initiatorgruppen anzuzeigen, führen Sie den Befehl igroup show aus.
+
....
igroup create –vserver Infra-SVM –igroup VM-Host-Infra-A –protocol iscsi –ostype vmware –initiator <<var_vm_host_infra_a_iSCSI-A_vNIC_IQN>>, <<var_vm_host_infra_a_iSCSI-B_vNIC_IQN>>
igroup create –vserver Infra-SVM –igroup VM-Host-Infra-B –protocol iscsi –ostype vmware –initiator <<var_vm_host_infra_b_iSCSI-A_vNIC_IQN>>, <<var_vm_host_infra_b_iSCSI-B_vNIC_IQN>>
....
+

NOTE: Dieser Schritt muss abgeschlossen sein, wenn zusätzliche Cisco UCS C-Series Server hinzugefügt werden.





== Zuordnen von Boot-LUNs zu Initiatorgruppen

Führen Sie die folgenden Befehle aus der SSH-Verbindung für das Cluster-Management aus, um Boot-LUNs Initiatorgruppen zuzuordnen:

....
lun map –vserver Infra-SVM –volume esxi_boot –lun VM-Host-Infra- A –igroup VM-Host-Infra- A –lun-id 0
lun map –vserver Infra-SVM –volume esxi_boot –lun VM-Host-Infra- B –igroup VM-Host-Infra- B –lun-id 0
....

NOTE: Dieser Schritt muss abgeschlossen sein, wenn zusätzliche Cisco UCS C-Series Server hinzugefügt werden.

link:express-c-series-aff220-deploy_vmware_vsphere_6.7_deployment_procedure.html["Weiter: VMware vSphere 6.7 Deployment Procedure."]
