---
sidebar: sidebar 
permalink: express/express-direct-attach-design_technology_requirements.html 
keywords: requirements, hardware, software, A220, HA, VIC, B200 m5, fabric interconnect, VMware, vCenter, Server, Appliance, ESXi, hypervisor 
summary: Ein FlexPod Express System erfordert eine Kombination aus Hardware- und Softwarekomponenten. FlexPod Express beschreibt außerdem die Hardwarekomponenten, die erforderlich sind, um dem System in Einheiten von zwei Hypervisor-Nodes hinzuzufügen. 
---
= Technologieanforderungen erfüllt
:allow-uri-read: 


Ein FlexPod Express System erfordert eine Kombination aus Hardware- und Softwarekomponenten. FlexPod Express beschreibt außerdem die Hardwarekomponenten, die erforderlich sind, um dem System in Einheiten von zwei Hypervisor-Nodes hinzuzufügen.



== Hardwareanforderungen

Unabhängig vom ausgewählten Hypervisor nutzen alle FlexPod Express Konfigurationen dieselbe Hardware. Daher kann auch bei sich ändernden Geschäftsanforderungen jeder Hypervisor auf derselben FlexPod Express Hardware ausgeführt werden.

In der folgenden Tabelle werden die Hardwarekomponenten aufgeführt, die für alle FlexPod Express Konfigurationen erforderlich sind.

[cols="50,50"]
|===
| Trennt | Menge 


| AFF A220 HA-PAAR | 1 


| Cisco UCS B200 M5 Server | 2 


| Cisco Nexus 31108PCV-Switch | 2 


| Cisco UCS Virtual Interface Card (VIC) 1440 für den B200 M5 Server | 2 


| Cisco UCS Mini mit zwei integrierten UCS-FI-M-6324 Fabric Interconnects | 1 
|===


== Softwareanforderungen

In der folgenden Tabelle werden die Softwarekomponenten aufgeführt, die für die Implementierung der Architekturen der FlexPod Express Lösungen erforderlich sind.

[cols="33,33,33"]
|===
| Software | Version | Details 


| Cisco UCS Manager | 4.0(1b) | Für Cisco UCS Fabric Interconnect FI-6324UP 


| Cisco Blade Software | 4.0(1b) | Für Cisco UCS B200 M5 Server 


| Cisco Nenic-Treiber | 1.0.25.0 | Für Cisco VIC 1440 Schnittstellenkarten 


| Cisco NX-OS | 7.0(3)I6(1) | Für Cisco Nexus 31108PCV Switches 


| NetApp ONTAP | 9.5 | Für AFF A220 Controller 
|===
In der folgenden Tabelle ist die erforderliche Software für alle VMware vSphere Implementierungen auf FlexPod Express aufgeführt.

[cols="50,50"]
|===
| Software | Version 


| VMware vCenter Server Appliance | 6.7U1 


| VMware vSphere ESXi Hypervisor | 6.7U1 
|===
link:express-direct-attach-design_design_choices.html["Als Nächstes: Design-Entscheidungen."]
