---
sidebar: sidebar 
permalink: express/express-c-series-aff220-deploy_deployment_procedures_overview.html 
keywords: vmware, vcenter, server, appliance, download 
summary: Dieses Dokument bietet Details zur Konfiguration eines vollständig redundanten, hochverfügbaren FlexPod Express Systems und zur Bereitstellung mehrerer Cisco UCS Hosts. 
---
= Implementierungsverfahren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Dieses Dokument enthält Details zur Konfiguration eines vollständig redundanten, hochverfügbaren FlexPod Express-Systems. Um diese Redundanz Rechnung zu tragen, werden die in jedem Schritt konfigurierten Komponenten entweder als Komponente A oder Komponente B bezeichnet Controller A und Controller B identifizieren beispielsweise die beiden NetApp Storage Controller, die in diesem Dokument bereitgestellt werden. Switch A und Switch B identifizieren ein Paar Cisco Nexus-Switches.

Zusätzlich beschreibt dieses Dokument Schritte zur Bereitstellung mehrerer Cisco UCS-Hosts, die sequenziell als Server A, Server B usw. identifiziert werden können.

Um anzugeben, dass Sie in einem Schritt Informationen zu Ihrer Umgebung angeben sollten, `\<<text>>` Wird als Teil der Befehlsstruktur angezeigt. Das folgende Beispiel enthält die `vlan create` Befehl:

....
Controller01>vlan create vif0 <<mgmt_vlan_id>>
....
Mit diesem Dokument können Sie die FlexPod Express Umgebung vollständig konfigurieren. Bei diesem Prozess müssen Sie in verschiedenen Schritten kundenspezifische Namenskonventionen, IP-Adressen und VLAN-Schemata (Virtual Local Area Network) einfügen. Die folgende Tabelle beschreibt die für die Implementierung erforderlichen VLANs, wie in diesem Leitfaden beschrieben. Diese Tabelle kann anhand der spezifischen Standortvariablen abgeschlossen und zur Implementierung der Konfigurationsschritte des Dokuments verwendet werden.


NOTE: Wenn Sie separate in-Band- und Out-of-Band-Management-VLANs verwenden, müssen Sie eine Layer-3-Route zwischen ihnen erstellen. Für diese Validierung wurde ein gemeinsames Management-VLAN genutzt.

|===
| EIN Name | VLAN-Zweck | ID zur Validierung dieses Dokuments verwendet 


| Management-VLAN | VLAN für Management-Schnittstellen | 3437 


| Natives VLAN | VLAN, dem nicht getaggte Frames zugewiesen sind | 2 


| NFS-VLAN | VLAN für NFS-Verkehr | 3438 


| VMware vMotion VLAN | VLAN, das für die Verschiebung von virtuellen Maschinen von einem physischen Host zum anderen bestimmt ist | 3441 


| Datenverkehr-VLAN für Virtual Machines | VLAN für den Datenverkehr von Virtual-Machine-Applikationen | 3442 


| ISCSI-A-VLAN | VLAN für iSCSI-Verkehr auf Fabric A | 3439 


| ISCSI-B-VLAN | VLAN für iSCSI-Datenverkehr auf Fabric B | 3440 
|===
Die VLAN-Nummern sind in der gesamten Konfiguration von FlexPod Express erforderlich. Die VLANs werden als bezeichnet `\<<var_xxxx_vlan>>`, Wo `xxxx` Dient dem VLAN (z. B. iSCSI-A).

In der folgenden Tabelle sind die erstellten virtuellen VMware-Maschinen aufgeführt.

|===
| Beschreibung der virtuellen Maschine | Host-Name 


| VMware vCenter Server |  
|===