---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_program_summary_overview.html 
keywords: fexpod, express, cisco, ucs, series, c, aff, c190, nva, deployment 
summary: FlexPod Datacenter und FlexPod Express bieten eine Basiskonfiguration, die sich flexibel für eine Vielzahl von Anwendungsfällen und Anforderungen dimensionieren und optimieren lässt. 
---
= NVA-1142-DEPLOY: FlexPod Express mit Cisco UCS C-Serie und NetApp AFF C190 Serie - NVA Deployment
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Savita Kumari, NetApp

[role="lead"]
Aktuell stellen immer mehr Unternehmen ihre Rechenzentren auf Shared IT-Infrastrukturen und Cloud Computing um. Außerdem wünschen sich Unternehmen eine einfache und effektive Lösung für Remote-Standorte und Zweigstellen, die Technologien einsetzen, die ihnen in ihrem Datacenter vertraut sind.

FlexPod Express ist eine vorkonfigurierte Datacenter-Architektur mit Best Practices, die auf Cisco Unified Computing System (Cisco UCS), der Cisco Nexus Switch-Produktfamilie und NetApp Storage-Technologien basiert. Die Komponenten eines FlexPod Express Systems sind wie ihre Kollegen im FlexPod Datacenter, die Managementsynergien über die gesamte IT-Infrastrukturumgebung hinweg in geringerem Umfang ermöglichen. FlexPod Datacenter und FlexPod Express sind optimale Plattformen für die Virtualisierung sowie für Bare-Metal-Betriebssysteme und Enterprise Workloads.

FlexPod Datacenter und FlexPod Express bieten eine Basiskonfiguration, die sich flexibel für eine Vielzahl von Anwendungsfällen und Anforderungen dimensionieren und optimieren lässt. Bestehende FlexPod Datacenter-Kunden können ihr FlexPod Express System mit den gewohnten Tools managen. Neue FlexPod Express Kunden können bei wachsenden Umgebungen mühelos auf das Management von FlexPod Datacenter umsteigen.

FlexPod Express ist die optimale Infrastrukturbasis für Remote-Standorte und externe Niederlassungen sowie für kleine bis mittelständische Unternehmen. Es ist außerdem eine optimale Lösung für Kunden, die eine Infrastruktur für einen dedizierten Workload bereitstellen möchten.

FlexPod Express bietet eine einfach zu managende Infrastruktur, die sich für fast alle Workloads eignet.
