---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_solution_overview.html 
keywords: flexpod, datacenter, technical specifications, platform, architecture 
summary: 'Die FlexPod Plattform ist eine vorkonfigurierte, nach Best Practices entwickelte Rechenzentrumsarchitektur, die auf dem Cisco Unified Computing System (Cisco UCS), der Cisco Nexus Familie von Switches und NetApp Storage Controllern (NetApp AFF, ASA, FAS oder AFX Systemen) basiert.' 
---
= Technische Spezifikationen für FlexPod Datacenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die FlexPod Plattform ist eine vorkonfigurierte, nach Best Practices entwickelte Rechenzentrumsarchitektur, die auf dem Cisco Unified Computing System (Cisco UCS), der Cisco Nexus und MDS (für FC) Familie von Switches sowie NetApp Storage Controllern (AFF, ASA, FAS oder AFX Systeme) basiert.

FlexPod ist eine geeignete Plattform für die Ausführung einer Vielzahl von Virtualisierungs-Hypervisoren sowie für Bare-Metal-Betriebssysteme und Enterprise Workloads. FlexPod bietet nicht nur eine Basiskonfiguration, sondern auch die Flexibilität, gemäß den Anforderungen vieler verschiedener Anwendungsfälle und Anwendungsfälle dimensioniert zu werden.


NOTE: Bevor Sie eine komplette FlexPod Konfiguration bestellen, finden Sie auf der  http://www.netapp.com/us/technology/flexpod["NetApp FlexPod Homepage"^] Seite die aktuelle Version dieser technischen Spezifikationen.

link:dc-tech-spec_flexpod_platforms.html["Als Nächstes: FlexPod Plattformen."]
