---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, cisco, ucs, fabric, interconnect, uplink, direct, san 
summary: Nachfolgend sind die Konnektivitätsanforderungen für die FlexPod-Konfiguration aufgeführt. 
---
= Konnektivitätsanforderungen erfüllen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Eine FlexPod-Konfiguration erfüllt die folgenden Konnektivitätsanforderungen:

* Für alle Komponenten ist ein separates Ethernet-/1 GB/s-Ethernet-Out-of-Band-Managementnetzwerk erforderlich.
* NetApp empfiehlt, die Jumbo Frame-Unterstützung in der gesamten Umgebung zu aktivieren, ist jedoch nicht erforderlich.
* Die Ports der Cisco UCS Fabric Interconnect Appliance werden nur für iSCSI- und NAS-Verbindungen empfohlen.
* Es können keine zusätzlichen Geräte zwischen den Kern-FlexPod-Komponenten angeordnet werden.


Uplink-Verbindungen:

* Die Ports auf den NetApp Storage Controllern müssen mit den Switches der Cisco Nexus 5000, 7000 oder 9000 Serie verbunden sein, um virtuelle Port-Kanäle (vPCs) zu unterstützen.
* VPCs sind von den Cisco Switches der Serie Nexus 5000, 7000 oder 9000 zu den NetApp Storage Controllern erforderlich.
* VPCs sind erforderlich für Cisco Switches der Nexus 5000, 7000 oder 9000 Serie zu Fabric Interconnects.
* Für einen vPC sind mindestens zwei Verbindungen erforderlich. Die Anzahl der Verbindungen innerhalb eines vPC kann abhängig von der Applikationslast und den Performance-Anforderungen erhöht werden.


Direkte Verbindungen:

* NetApp Storage Controller Ports, die direkt mit Fabric Interconnects verbunden sind, können gruppiert werden, um einen Port Channel zu unterstützen. VPC wird für diese Konfiguration nicht unterstützt.
* Für End-to-End FCoE-Designs werden FCoE-Port-Channel empfohlen.


SAN Booting:

* FlexPod Lösungen wurden auf eine SAN Boot-Architektur mit iSCSI-, FC- oder FCoE-Protokollen ausgerichtet. Durch die Verwendung von Boot-from-SAN-Technologien wird die flexibelste Konfiguration für die Datacenter-Infrastruktur erzielt, sodass die umfassenden Funktionen, die innerhalb jeder Infrastrukturkomponente zur Verfügung stehen, ermöglicht werden. Obwohl das Booten über SAN die effizienteste Konfiguration ist, ist das Booten über lokalen Server Storage eine gültige und unterstützte Konfiguration.
* SAN-Boot über FC-NVME wird nicht unterstützt.

