---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_legacy_equipment.html 
keywords: legacy, equipment, cisco, end, life, eol, flexpod, datacenter, technical, specifications 
summary: 'FlexPod ist eine flexible Lösung, mit der Sie Ihre vorhandenen Systeme und neue Systeme, die derzeit von Cisco und NetApp verkauft werden, nutzen können. Gelegentlich werden bestimmte Modelle von Geräten von Cisco und NetApp als End-of-Life (EOL) bezeichnet.' 
---
= Altgeräte
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
FlexPod ist eine flexible Lösung, mit der Sie Ihre vorhandenen Systeme und neue Systeme, die derzeit von Cisco und NetApp verkauft werden, nutzen können. Gelegentlich werden bestimmte Modelle von Geräten von Cisco und NetApp als End-of-Life (EOL) bezeichnet.

Auch wenn diese Modelle nicht mehr verfügbar sind, wenn Sie vor dem Datum der Einstellung der Verfügbarkeit (EOA) eines dieser Modelle gekauft haben, können Sie diese Systeme in einer FlexPod Konfiguration verwenden. Auf der finden Sie eine vollständige Liste der älteren Modelle, die in FlexPod unterstützt werden und die nicht mehr verkauft werden können https://mysupport.netapp.com/info/eoa/index.html["NetApp Service und Support Produktprogramme, deren Ende der Verfügbarkeit Index erreicht ist"^].

Weitere Informationen zu älteren Cisco Systemen finden Sie in den Cisco EOL- und EOA-Mitteilungen für http://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-c-series-rack-servers/eos-eol-notice-listing.html["Cisco UCS C-Serie Rack Server"^], http://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-b-series-blade-servers/eos-eol-notice-listing.html["Blade Server der Cisco UCS B-Serie"^], und https://www.cisco.com/c/en/us/products/eos-eol-listing.html["Nexus Switches"^].

Unterstützung für ältere FC-Fabric-Systeme umfasst:

* 2 GB Fabric
* 4 GB Fabric


Ältere Software umfasst Folgendes:

* NetApp Data ONTAP in 7-Mode, 7.3.5 und höher
* ONTAP 8.1.x bis 9.0.x
* Cisco UCS Manager 1.3 und höher
* Cisco UCS Manager 2.1 bis 2.2.7

