---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_automation.html 
keywords: flexpod datacenter, automation, IaC, GitHub repository, Ansible 
summary: Die automatisierte Bereitstellung für FlexPod Datacenter ist über ein GitHub Repository möglich, das Ansible-Playbooks und zugehörige Infrastructure-as-Code-Assets enthält. 
---
= Automatisierte Bereitstellung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Die automatisierte Bereitstellung von FlexPod Datacenter ist über das FlexPod Datacenter link:https://github.com/ucs-compute-solutions["GitHub-Repositories"^] verfügbar. Diese Repositories enthalten Ansible Playbooks und zugehörige Dateien, um die Bereitstellung der FlexPod Datacenter Infrastruktur als Code (IaC) zu erleichtern.

Die GitHub Repositories bieten einen strukturierten Ansatz für die Bereitstellung von FlexPod Datacenter-Konfigurationen und ermöglichen es Benutzern, die Einrichtung und Verwaltung ihrer Infrastruktur zu automatisieren. Diese enthalten Playbooks für verschiedene Komponenten des FlexPod Datacenter-Designs, wodurch eine effiziente, konsistente und zuverlässige Bereitstellung und Wartung ihrer Umgebungen sichergestellt wird.

* Automatisierte Bereitstellung von FlexPod Datacenter mit Basis-Konfiguration
+
** Für die automatisierte Bereitstellung einer Basis FlexPod Datacenter-Konfiguration mit Cisco Nexus Switches, Cisco UCS C-Series Servern oder Cisco UCS X-Series Direct mit IMM und NetApp ONTAP finden sich Informationen in der link:https://github.com/ucs-compute-solutions/FlexPod-Base-IMM["FlexPod Datacenter Basis-Konfiguration mit Cisco IMM und NetApp ONTAP GitHub Repository"^] und der entsprechenden link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_base_imm_m7_iac.html["CVD"^].
** Dieses Repository enthält Ansible-Playbooks und zugehörige Dateien, um die Bereitstellung einer Basis-FlexPod Datacenter-Konfiguration zu erleichtern. Mandanten für verschiedene Hypervisoren, Bare-Metal-Betriebssysteme und Anwendungen können anschließend auf FlexPod Base konfiguriert werden.


* Automatisierte Bereitstellung von FlexPod Datacenter mit VMware vSphere und Cisco IMM
+
** Für die automatisierte Bereitstellung einer FlexPod Datacenter Konfiguration mit Cisco Nexus Switches, Cisco UCS C-Series Servern oder Cisco UCS X-Series Direct mit IMM und NetApp ONTAP mit VMware vSphere wird auf die link:https://github.com/ucs-compute-solutions/FlexPod-IMM-VMware["FlexPod Datacenter mit VMware vSphere und Cisco IMM GitHub Repo"^] und die entsprechende link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_imm_m7_iac.html["CVD"^] verwiesen.
** Die in den Ansible Playbooks definierten VMware Rollen können für VMware bezogene Konfigurationen verwendet werden.





NOTE: In diesem Repository ist FC-Boot mit FC-NVMe und NFS standardmäßig in den Variablendateien konfiguriert, aber iSCSI-Boot und NVMe-TCP mit NFS können ebenfalls verwendet werden.

* Automatisierte Bereitstellung von FlexPod Datacenter mit Red Hat OpenShift und Cisco IMM
+
** Für die automatisierte Bereitstellung einer FlexPod Datacenter Konfiguration mit Cisco Nexus Switches, Cisco UCS X-Series Direct mit IMM und NetApp ONTAP mit Red Hat OpenShift siehe link:https://github.com/ucs-compute-solutions/FlexPod-IMM-OpenShift["FlexPod Datacenter mit Red Hat OpenShift und Cisco IMM GitHub Repo"^].
** Dieses Repository kann zur Einrichtung von Cisco Geräten und NetApp ONTAP Storage als Vorbereitung auf die Installation von Red Hat OpenShift verwendet werden, wie im link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_rh_openshift_bm_iac_deploy.html["CVD"^] beschrieben.





NOTE: Dieses Repository bietet Optionen zur Konfiguration des lokalen Bootvorgangs mit den Speicherprotokollen NFS, iSCSI, NVMe-TCP und ONTAP S3.
