---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_netapp_components.html 
keywords: storage, controllers, cluster, aff, asa, fas, afx, ontap, interconnect switches, drives, disk, shelves, licensing, options 
summary: NetApp Storage-Controller bilden die Storage-Grundlage in der FlexPod-Architektur für Boot- und Applikationsdaten-Storage. NetApp Komponenten umfassen Storage Controller, Cluster Interconnect Switches, Laufwerke und Festplatten-Shelfs sowie Lizenzoptionen. 
---
= Komponenten von NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Storage-Controller bilden die Storage-Grundlage in der FlexPod-Architektur für Boot- und Applikationsdaten-Storage. NetApp Komponenten umfassen Storage Controller, Cluster Interconnect Switches, Laufwerke und Festplatten-Shelfs sowie Lizenzoptionen.



[[netapp-storage-controller-options]]
== Optionen für NetApp Storage Controller

Redundante NetApp FAS, AFF, ASA oder AFX Controller sind in der FlexPod Architektur erforderlich. Die Controller führen ONTAP Software aus. Bei der Bestellung der Storage Controller kann die bevorzugte Softwareversion auf den Controllern vorinstalliert werden. Für ONTAP wird ein kompletter Cluster bestellt. Ein kompletter Cluster umfasst ein Paar Storage Controller und eine Cluster-Interconnect (Switch oder Cluster ohne Switches).


NOTE: Eine Cluster ohne Switches Konfiguration wird nur für eine Zwei-Node-Cluster-Konfiguration unterstützt. Cluster-Interconnect-Switches sind für Konfigurationen mit vier oder mehr Knoten erforderlich und für eine Zwei-Node-Cluster-Konfiguration optional.

Abhängig von der ausgewählten Storage-Plattform stehen verschiedene Optionen und Konfigurationen zur Verfügung. Details zu diesen zusätzlichen Komponenten finden Sie von Ihrem Ansprechpartner.

Die in der nachstehenden Tabelle aufgeführten Controller-Familien eignen sich für die Verwendung in einer FlexPod Datacenter-Lösung, da ihre Verbindung zu den Cisco Nexus-Switches nahtlos ist. Siehe https://hwu.netapp.com/["NetApp Hardware Universe"^] Für bestimmte Kompatibilitätsdetails zu jedem Controller-Modell.

|===
| NetApp Speicherfamilie für FlexPod Datacenter | Modell | Technische Spezifikationen 


.6+| AFF A-Serie | AFF A20 .6+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["AFF A-Series Datenblatt"] 


| AFF A30 


| AFF A50 


| AFF A70 


| AFF A90 


| AFF A1K 


.3+| AFF C-Series | AFF C30 .3+| https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["AFF C-Series Datenblatt"] 


| AFF C60 


| AFF C80 


.7+| ASA | ASA A20 .7+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA Datenblatt"] 


| ASA A30 


| ASA C30 


| ASA A50 


| ASA A70 


| ASA A90 


| ASA A1K 


.5+| FAS | FAS2750 .5+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS Datenblatt"] 


| FAS2820 


| FAS50 


| FAS70 


| FAS90 


.2+| AFX | AFX 1K .2+| https://www.netapp.com/pdf.html?item=/media/142853-ds-3466-netapp-afx-datasheet.pdf["AFX Datenblatt"] 


| AFX 2K 
|===


[[cluster-interconnect-switch-options]]
== Optionen für Cluster-Interconnect-Switches

Die folgende Tabelle listet die Nexus Cluster-Interconnect-Switches auf, die für FlexPod Architekturen verfügbar sind. FlexPod unterstützt alle von ONTAP unterstützten Cluster-Switches, einschließlich Nicht-Cisco-Switches, sofern sie mit der eingesetzten ONTAP-Version kompatibel sind.

Eine Liste der unterstützten Cluster InterConnect Switches finden Sie unter https://hwu.netapp.com/["NetApp Hardware Universe"^], indem Sie auf *Products > Networking > Switches* klicken und anschließend *Cluster InterConnect Switch* auswählen. Es besteht die Möglichkeit, nach Herstellertyp zu filtern, einen Switch auszuwählen und auf *Show results* zu klicken, um detaillierte Informationen zum Switch anzuzeigen.

Die folgende Tabelle listet die Cisco Switches auf, die als Cluster Interconnect Switch verwendet werden können.

|===
| Cluster-Interconnect-Switch | Technische Spezifikationen 


| Cisco Nexus 9336C-FX2 | https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/configure-switch-overview-9336c-cluster.html["NetApp Dokumentation: Cisco Nexus 9336C-FX2 Switches"^] 
|===


[[netapp-disk-shelf-and-drive-options]]
== NetApp Platten-Shelf- und Laufwerksoptionen

Für Storage-Controller, die kein integriertes Disk-Shelf besitzen, ist mindestens ein NetApp Disk-Shelf erforderlich. Der ausgewählte NetApp Shelf-Typ bestimmt, welche Laufwerkstypen in diesem Shelf verfügbar sind.


NOTE: Alle Festplatten-Shelfs und Festplatten-Teilenummern können bei Ihrem Vertriebsmitarbeiter angegeben werden.

Die folgende Tabelle listet die NetApp Disk Shelf-Optionen für FlexPod Datacenter zusammen mit Links zu deren technischen Spezifikationen auf.

Um die Liste der für Ihr Disk Shelf unterstützten Laufwerke zu erhalten, gehen Sie zu link:https://hwu.netapp.com/["NetApp Hardware Universe"^], wählen Sie unter *Products > Storage > Shelves* *ONTAP (AFF, ASA, FAS) oder ONTAP (AFX)* aus, wählen Sie die von Ihnen verwendete ONTAP-Version, dann den Shelf-Typ (zum Beispiel: *DS212C*) und klicken Sie auf *Show Results*. Mit einem Klick auf *Supported Drives* werden die für bestimmte Versionen von ONTAP und die Disk Shelves unterstützten Laufwerke angezeigt.

|===
| Festplatten-Shelf | Technische Spezifikationen 


| DS212C .6+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["Festplattengehäuse und Speichermedien"] 


| DS224C 


| DS460C 


| NS224 


| NS224 mit NSM100B 


| NX224 
|===


[[netapp-software-licensing-options]]
== NetApp Software-Lizenzoptionen

Die folgende Tabelle listet die NetApp Softwarelizenzierungsoptionen auf.

|===
| NetApp Softwarelizenzierung | Technische Spezifikationen 


| ONTAP One für AFF, FAS und AFX .2+| Wenden Sie sich an Ihr NetApp Vertriebsteam, um weitere Lizenzierungsinformationen zu erhalten. 


| ONTAP One für SAN für ASA 
|===
Weitere Informationen zur NetApp Softwarelizenzierung sind unter folgendem Link verfügbar:  https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["NetApp Softwarelizenzierung"^].



[[netapp-support-licensing-options]]
== NetApp Support – Lizenzoptionen

SupportEdge Premium-Lizenzen sind erforderlich, und die Teilenummern für diese Lizenzen variieren je nach den im FlexPod Datacenter Design ausgewählten Optionen.

Die folgende Tabelle listet die NetApp Support-Lizenzierungsoptionen für NetApp AFF, ASA, FAS und AFX Storage-Systeme auf.

|===
| Lizenzierung des NetApp Supports | Technische Spezifikationen 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===