---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, datacenter, netapp, cisco, ucs, disk shelves 
summary: Dieser Abschnitt beschreibt die Stromversorgungsanforderungen und die Richtlinien für die Verkabelung der Festplattengehäuse für ein FlexPod Datacenter-Design. 
---
= Richtlinien für Stromversorgung und Verkabelung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieser Abschnitt beschreibt die Stromversorgungsanforderungen und Verkabelungsrichtlinien für ein FlexPod Datacenter Design.



[[power-requirements]]
== Stromversorgung

Die Stromanforderungen für das FlexPod Datacenter unterscheiden sich je nach Installationsort der FlexPod Datacenter Konfiguration.

Weitere Informationen über die maximale Leistung, die benötigt wird, und weitere detaillierte Informationen zur Stromversorgung finden Sie in den technischen Spezifikationen für jede im Abschnitt aufgeführte Hardware-Komponente link:dc-tech-spec_technical_specifications_and_references.html["Technische Spezifikationen und Referenzen: Hardware-Komponenten"].

Detaillierte Cisco UCS Leistungsdaten sind unter  https://ucspowercalculator.cisco.com/["Cisco UCS – Stromversorgungsrechner"^] zu finden.

Informationen zu Stromdaten des NetApp Speichercontrollers finden sich im https://hwu.netapp.com/["NetApp Hardware Universe"^]. Unter *Plattformen* die gewünschte Speicherplattform auswählen (zum Beispiel AFF A90), die ONTAP-Version auswählen und dann auf *Ergebnisse anzeigen* klicken. Netzkabeldaten sind im Abschnitt *Unterstützte Netzkabel* aufgeführt. Einzelheiten zu Größe, Gewicht, Wattzahl usw. stehen im Abschnitt *Größe, Gewicht, Geräuschentwicklung, Stromversorgung*.



[[cabling-guidelines]]
== Verkabelungsrichtlinien

Dieser Abschnitt enthält allgemeine Verkabelungsrichtlinien für ein FlexPod Datacenter Design.

* Redundante Konnektivität für die Compute- und Storage-Verbindungen sicherstellen.
* Die Geschwindigkeit der Verbindungen muss mit den angeschlossenen Komponenten kompatibel sein.
* Im Abschnitt link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html["FlexPod Datacenter-Topologien"^] sind zusätzliche Verkabelungsrichtlinien für spezifische Topologien aufgeführt.


Die folgende Tabelle enthält Verkabelungsrichtlinien für NetApp Festplattengehäuse, die in einem FlexPod Datacenter-Design verwendet werden können.

|===


| Festplatten-Shelf | Verkabelungsrichtlinien 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["SAS-Verkabelungsregeln"^] 


| DS224C 


| DS460C 


| NS224 .3+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["Anforderungen und Best Practices für NS224 und NX224 Gehäuse"^] 


| NS224 mit NSM100B 


| NX224 
|===