---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_supported_versus_validated_flexpod_configurations.html 
keywords: flexpod, architecture, supported, validated, configurations, hardware, software 
summary: Die FlexPod-Architektur wird durch den Satz von Regeln definiert, die in diesem Dokument beschrieben werden. 
---
= Unterstützte und validierte FlexPod Konfigurationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Die FlexPod-Architektur wird durch den Satz von Regeln definiert, die in diesem Dokument beschrieben werden. Die Hardwarekomponenten und Softwarekonfigurationen müssen vom unterstützt werden https://ucshcltool.cloudapps.cisco.com/public/["Cisco UCS Hardware- und Software-Kompatibilitätsliste"^] Und das http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool (IMT)"^].

Jedes Cisco Validated Design (CVD) oder jede NetApp Verified Architecture (NVA) ist eine mögliche FlexPod-Konfiguration. Cisco und NetApp dokumentieren diese Konfigurationskombinationen und validieren sie in umfangreichen End-to-End-Tests. Von diesen Konfigurationen abweichende FlexPod-Implementierungen werden vollständig unterstützt, wenn sie den Richtlinien in diesem Dokument folgen und alle Komponenten in der Cisco UCS Hardware- und Software-Kompatibilitätsliste und der NetApp als kompatibel aufgeführt sind http://mysupport.netapp.com/matrix["IMT"^].

Beispielsweise werden beim Hinzufügen weiterer Storage-Controller oder Cisco UCS Server und beim Upgrade von Software auf neuere Versionen vollständig unterstützt, wenn die Software, Hardware und Konfigurationen den in diesem Dokument definierten Richtlinien entsprechen.
