---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_cisco_components.html 
keywords: cisco, components, ucs, fabric, interconnect, server, rack, apic, nexus, software, support, mds, x-series-modular, x-series-direct 
summary: Cisco hat maßgeblich zum Design und zur Architektur von FlexPod beigetragen und deckt sowohl die Compute- als auch die Netzwerkschicht der Lösung ab. In diesem Abschnitt werden die Cisco UCS- und Cisco Nexus-Optionen beschrieben, die für FlexPod verfügbar sind. 
---
= Komponenten von Cisco
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cisco hat maßgeblich zum Design und zur Architektur von FlexPod beigetragen und deckt sowohl die Compute- als auch die Netzwerkschicht der Lösung ab. In diesem Abschnitt werden die für FlexPod verfügbaren Cisco UCS-, Nexus- und MDS-Optionen beschrieben.



[[cisco-ucs-fabric-interconnect-options]]
== Cisco UCS Fabric Interconnect-Optionen

In der FlexPod Architektur sind redundante Fabric Interconnects erforderlich. Wenn Sie einem Paar Fabric Interconnects mehrere Cisco UCS Gehäuse hinzufügen, beachten Sie, dass die maximale Anzahl an Gehäusen in einer Umgebung von einer Architektur und einem Port-Limit abhängig ist.

Die in der folgenden Tabelle aufgeführten Teilenummern beziehen sich auf die Basis-Fabric-Verbindungen. Sie beinhalten nicht das Netzteil (PSU) oder SFP+, QSFP+ oder Erweiterungsmodule.

|===
| Cisco UCS Fabric Interconnect | Teilenummer | Technische Spezifikationen 


| Cisco UCS 6664 | UCS-FI-6664-U .2+| https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-6600-series-fabric-interconnect-specsheet.pdf["Cisco UCS 6600 Series Fabric Interconnect"] 


| Cisco UCS 6652 | UCS-FI-6652-U 


| Cisco UCS 6536 | UCSX-FI-6536-U | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-6536-fabric-interconnect-spec-sheet.pdf["Cisco UCS 6536 Fabric Interconnect"] 


| Cisco UCS 6454 | UCS-FI-6454-U .2+| https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/6400-specsheet.pdf["Cisco UCS 6400 Series Fabric Interconnect"] 


| Cisco UCS 64108 | UCS-FI-64108-U 


| UCS 9108 100G Fabric Interconnect (Cisco UCS X-Series Direct) | UCSX-S9108-100G | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf["Cisco UCS 9108 Fabric Interconnect"] 
|===


[[cisco-ucs-x-series-chassis-option]]
== Cisco UCS X-Serie: Gehäuseoption

Zur Verwendung der Computing-Nodes der Cisco UCS X-Serie müssen Sie ein Chassis der Cisco UCS X-Serie haben. In der folgenden Tabelle wird die Gehäuseoption des Cisco UCS X-Series beschrieben.

|===
| Cisco UCS X-Serie Blade | Teilenummer | Technische Spezifikationen 


| Cisco UCS X9508 Chassis | UCSD-9508 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html?ccid=cc002456&oid=dstcsm026317["Cisco UCS X9508 Chassis"] 
|===
Jedes Cisco UCS 9508 Chassis muss über zwei Cisco UCS 9108 Intelligent Fabric Modules (IFMS) verfügen, um redundante Konnektivität zu den Fabric Interconnects bereitzustellen.



[[cisco-ucs-x-series-device-options]]
== Optionen für Cisco UCS X-Series Geräte

Cisco UCS X-Series Computing-Nodes stehen mit unterschiedlichen CPU-, Speicher- und I/O-Optionen zur Verfügung. Die in der folgenden Tabelle aufgeführten Teilenummern gelten für den Basis-Node. Sie enthalten keine CPU, Arbeitsspeicher, Laufwerke oder Mezzanine-Adapterkarten. Es sind mehrere Konfigurationsoptionen verfügbar, die in der FlexPod-Architektur unterstützt werden.

|===
| Cisco UCS X-Serie Computing-Nodes | Teilenummer | Technische Spezifikationen 


| Cisco UCS X210c M7 | UCSX-210C-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html["Cisco UCS X210c M7 Compute Node"] 


| Cisco UCS X210c M8 | UCSX-210C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html["Cisco UCS X210c M8 Compute Node"] 


| Cisco UCS X215c M8 | UCSX-215C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html["Cisco UCS X215c M8 Compute Node"] 


| Cisco UCS X410c M7 | UCSX-410C-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html["Cisco UCS X410c M7 Compute Node"] 


| Cisco UCS X410c M8 | UCSX-410C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html["Cisco UCS X410c M8 Compute Node"] 
|===
Die folgende Tabelle listet die für das Cisco UCS X-Series Chassis verfügbaren PCI Express-Knoten auf.

|===
| Cisco UCS X-Series PCIe Knoten | Teilenummer | Technische Spezifikationen 


| Cisco UCS X580p PCIe Node | UCSX-580P-U | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x580p-pcie-node-ds.html["Cisco UCS X580p PCIe Node"] 


| Cisco UCS X440p PCIe Node | UCSX-440P | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x440p-pcle-node-ds.html["Cisco UCS X440p PCIe Node"] 
|===
Die folgende Tabelle listet die für das Cisco UCS X-Series Chassis verfügbaren X-Fabric Module auf.

|===
| Cisco UCS X-Series X-Fabric Module | Teilenummer | Technische Spezifikationen 


| Cisco UCS 9108 Intelligent Fabric Module | UCSX-I-9108-100G | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-9108-100g-intelligent-fabric-module-spec-sheet.pdf["Cisco UCS 9108 Intelligent Fabric Module"] 


| Cisco UCS X9516 X-Fabric-Modul | UCSX-FS-9516 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-9516-x-fabric-module-ds.html["Cisco UCS X9516 X-Fabric-Modul"] 


| Cisco UCS X9416 X-Fabric-Modul | UCSX-F-9416 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/solution-overview-c22-2432175.html?ccid=cc002456&oid=sowcsm025665["Cisco UCS X9416 X-Fabric-Modul"] 
|===


[[cisco-ucs-x-series-modular-system]]
== Cisco UCS X-Series Modular System

Das Cisco UCS X-Series Modular System beginnt mit dem Cisco UCS X9508 Server Chassis, das für Anpassungsfähigkeit und Zukunftsfähigkeit entwickelt wurde. Das Chassis verfügt über ein einheitliches Ethernet-Fabric mit Cisco UCS Intelligent Fabric Modules und Cisco UCS X-Fabric Technology für andere Technologien. An der oberen Rückseite des Chassis befinden sich zwei intelligente Fabric Modules, die das Chassis mit den Upstream Cisco UCS 6400-, 6500- und UCS 6600-Series Fabric Interconnects verbinden.

Einen schnellen Überblick über die Funktionen und Möglichkeiten der Cisco UCS X-Series bietet link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-modular-system-aag.html["Cisco UCS X-Series Modular System auf einen Blick"^].

Die Cisco UCS X215c M8, Cisco UCS X210c und Cisco UCS X410c Compute Nodes bieten die Funktionalitäten von Blade- und Rack-Servern, da sie Rechendichte, Speicherkapazität und Erweiterbarkeit in einem einzigen Formfaktor vereinen.

Der Cisco UCS X440p PCIe Node unterstützt das Hinzufügen von GPUs mit PCIe Gen 4.0 mit dem Cisco UCS X9416 X-Fabric Module. Der Cisco UCS X580p PCIe Node unterstützt das Hinzufügen von GPUs mit PCIe Gen 5.0 mit dem Cisco UCS X9516 X-Fabric Module.

Weitere Informationen zu den Komponenten der Cisco UCS X-Series Modular System Lösung finden sich in den technischen Spezifikationen der einzelnen Komponenten in den vorangegangenen Abschnitten.


NOTE: Die vollständigen technischen Spezifikationen des Cisco UCS X-Series Modular Systems sind unter folgendem Link verfügbar: link:https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-x-series-modular-system/datasheet-listing.html["Cisco UCS X-Series Modular System"^]



[[cisco-ucs-x-series-direct-options]]
== Cisco UCS X-Series Direktoptionen

Cisco UCS X-Series Direct ist eine neue Architektur, die ein Paar Cisco UCS Fabric Interconnect 9108 100G mit Cisco UCS X9508 Chassis und Cisco UCS X-Series Compute nodes integriert, um die UCS X-Series Direct Lösung bereitzustellen.

Einen schnellen Überblick über die Funktionen und Möglichkeiten der Cisco UCS X-Series bietet link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-aag.html["Cisco UCS X-Series Direct auf einen Blick"^].

Cisco UCS X-Series Direct besteht aus den folgenden Komponenten:

* Cisco UCS 9108 100G Fabric Interconnect
* Cisco UCS X9508 Chassis
* Cisco UCS X-Series Compute-Knoten
* Optionale Komponenten:
+
** PCIe Nodes und X-Fabric Module
** Zweites Cisco UCS X9508 Chassis mit X-Series Compute Nodes und Cisco UCS 9108-100G Intelligent Fabric Modules und bis zu vier C-Series Rack Servern




Weitere Informationen zu den Komponenten der Cisco UCS X-Series Direct Lösung finden sich in den technischen Spezifikationen der einzelnen Komponenten in den vorangegangenen Abschnitten.


NOTE: Die vollständigen technischen Spezifikationen von Cisco UCS X-Series Direct sind unter folgendem Link verfügbar:  https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-ds.html["Cisco UCS X-Series Direkt-Datenblatt"].



[[cisco-ucs-c-series-rack-server-options]]
== Cisco UCS C-Series Rack Server Optionen

Cisco UCS C-Series Rack Server sind in Varianten mit einer, zwei und vier Höheneinheiten (HE) erhältlich, mit verschiedenen CPU-, Speicher- und I/O-Optionen. Die in der zweiten Tabelle unten aufgeführten Teilenummern beziehen sich auf den Basis-Server. Sie beinhalten keine CPUs, Speicher, Laufwerke oder Peripheral Component Interconnect Express (PCIe)-Karten. Mehrere Konfigurationsoptionen sind verfügbar und werden in der FlexPod Architektur unterstützt.

In der folgenden Tabelle werden die Optionen für Cisco UCS Rack Server der C-Serie aufgeführt.

|===
| Cisco UCS C-Series Rack Server | Teilenummer | Technische Spezifikationen 


| Cisco UCS C220 M7 | UCSC-C220-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html["Cisco UCS C220 M7 Rack Server"] 


| Cisco UCS C220 M8 | UCSC-C220-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html["Cisco UCS C220 M8 Rack Server"] 


| Cisco UCS C225 M8 | UCSC-C225-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m8-rack-server-ds.html["Cisco UCS C225 M8 Rack Server"] 


| Cisco UCS C240 M7 | UCSC-C240-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html["Cisco UCS C240 M7 Rack Server"] 


| Cisco UCS C240 M8 | UCSC-C240-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html["Cisco UCS C240 M8 Rack Server"] 


| Cisco UCS C245 M8 | UCSC-C245-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html["Cisco UCS C245 M8 Rack Server"] 
|===
Die folgende Tabelle listet die für KI-Anwendungsfälle optimierten Cisco UCS C-Series Rack-Server auf:

|===
| Rack Server der Cisco UCS C-Serie | Teilenummer | Technische Spezifikationen 


| Cisco UCS C845A M8 | UCSC-C845A-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c845a-m8-rack-server-ds.html["Cisco UCS C845A M8 Rack Server"] 


| Cisco UCS C880A M8 | UCSC-C880A-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c880a-m8-rack-server-ds.html["Cisco UCS C880A M8 Rack Server"] 
|===
Frühere Generationen von Cisco UCS C-Series Servern können in der FlexPod-Architektur verwendet werden, wenn sie auf der  https://ucshcltool.cloudapps.cisco.com/public/["Cisco UCS Hardware- und Software-Kompatibilitätsliste"^] unterstützt werden.



[[cisco-nexus-9000-series-switch-options]]
== Switch-Optionen für die Cisco Nexus 9000 Serie

Redundante Switches der Cisco Nexus 9000 Series sind in der FlexPod-Architektur erforderlich. Die in der folgenden Tabelle aufgeführten Teilenummern beziehen sich auf das Cisco Nexus 9000 Series Chassis; sie beinhalten keine SFP- oder Ethernet-Module.

|===
| Cisco Nexus Switch Fixed | Technische Spezifikationen 


| Cisco Nexus 9200-Serien-Switch | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html["Switches Der Cisco Nexus 9200-Serie"] 


| Cisco Nexus 9300-Serien-Switch | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["Switches Der Cisco Nexus 9300-Serie"] 
|===
|===
| Cisco Nexus Switch Modular | Technische Spezifikationen 


| Cisco Nexus 9400-Serien-Switch | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9400-series-switches-ds.html?ccid=cc002962&oid=dstdnc029385["Switches der Cisco Nexus 9400 Serie"] 


| Cisco Nexus 9500-Serien-Switch | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-729404.html["Switches Der Cisco Nexus 9500-Serie"] 


| Cisco Nexus 9800-Serien-Switch | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9800-series-switches-ds.html?ccid=cc002962&oid=dstdnc029386["Switches der Cisco Nexus 9800 Serie"] 
|===


[[cisco-apic-options]]
== Cisco APIC-Optionen

Cisco APIC ist die zentrale Architekturkomponente von Cisco ACI. Es bietet zentralisierte Verwaltung, Richtlinienkontrolle und Automatisierung für Cisco ACI Fabrics.

Weitere Informationen zu den APIC-Produktspezifikationen sind Tabelle 1 bis Tabelle 3 auf der  https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/application-policy-infrastructure-controller-apic/datasheet-c78-739715.html["Datenblatt Zum Cisco Application Policy Infrastructure Controller"^] zu entnehmen.



[[cisco-mds-options]]
== Cisco MDS Optionen

Cisco MDS Switches sind zwar ein optionales Element der FlexPod Architektur, jedoch müssen Implementierungen, die Fibre Channel SAN-Konnektivität für leistungsstärkeren Speicherzugriff nutzen, redundante Cisco MDS Switch Fabrics implementieren, um eine hochverfügbare SAN-Infrastruktur bereitzustellen. Die folgende Tabelle listet die unterstützten Cisco MDS Switches auf. Siehe die  https://imt.netapp.com["NetApp IMT"^] und  https://ucshcltool.cloudapps.cisco.com/public/["Cisco Hardware- und Software-Kompatibilitätsliste"^] für eine vollständige Liste der unterstützten SAN Switches.

|===
| Cisco MDS Switch | Beschreibung 


| Cisco MDS 9100 Multilayer-Fabric-Switches | http://www.cisco.com/c/en/us/products/storage-networking/mds-9100-series-multilayer-fabric-switches/datasheet-listing.html["Switches der Cisco MDS 9100 Serie"] 


| Cisco MDS 9200 Multiservice Switches | https://www.cisco.com/c/en/us/products/storage-networking/mds-9200-series-multiservice-switches/datasheet-listing.html["Switches der Cisco MDS 9200 Serie"] 


| Cisco MDS 9300 Multilayer Fabric Switches | https://www.cisco.com/c/en/us/products/storage-networking/mds-9300-series-multilayer-fabric-switches/datasheet-listing.html["Switches der Cisco MDS 9300 Serie"] 


| Cisco MDS 9700 Multilayer Directors | http://www.cisco.com/c/en/us/products/storage-networking/mds-9700-series-multilayer-directors/datasheet-listing.html["Cisco MDS 9700 Series Switches"] 
|===


[[cisco-support-licensing-options]]
== Cisco Support-Lizenzoptionen


NOTE: Es wird empfohlen, die Lizenzanforderungen vor der Bestellung mit Ihrem Cisco- oder NetApp-Vertriebsmitarbeiter abzuklären.

link:https://www.cisco.com/c/dam/en_us/about/doing_business/legal/service_descriptions/docs/solution-support-smart-total-care.pdf["Cisco Solution Support"^] ist ein Angebot für technischen Support, das für Cisco Lösungen gilt, die sowohl Hardware als auch Software von Cisco oder von Cisco und Solution Support Alliance Partnern umfassen und ausschließlich aus Cisco Produkten und Produkten von Drittanbietern (Solution Support Alliance Partner(s)) bestehen.

Cisco unterstützt komplexe Kundenumgebungen durch sein link:https://www.cisco.com/c/en/us/support/web/tac/technical-services-resource-guide.html["Technisches Unterstützungszentrum"]. Cisco Solution Support berechtigt Kunden zum Zugriff auf ein Team von TAC-Ingenieuren, die als Hauptansprechpartner für Probleme innerhalb der Lösung sowie für den Produktsupport für die Hardware und Software, die die Lösung bilden, fungieren.

Cisco nutzt das link:https://www.tsanet.org/cisco-tsanet-case-study/["TSANet Partnerprogramm"^] Framework, um Solution Support Partners in eine private Gruppe im TSANet Connect System aufzunehmen. TSANet Connect bietet eine einheitliche Methode für Support-Ingenieure zur Zusammenarbeit mit den technischen Teams der Partner, wodurch eine effiziente Kommunikation und eine beschleunigte Problemlösung ohne die durch informelle Kooperationsversuche entstehenden Reibungsverluste sichergestellt werden.
