---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_cisco_nexus_switching_modes_of_operation.html 
keywords: cisco, nexus, nx-os, aci, switching, modes, operation, datacenter, technical, specifications 
summary: Verschiedene Cisco Nexus-Produkte können als Switching-Komponente für eine gegebene FlexPod Installation verwendet werden. Die meisten dieser Optionen nutzen die Cisco NX-OS Software. Die Cisco Nexus Switch-Familie bietet innerhalb ihrer Produktlinien unterschiedliche Funktionen. Diese Funktionen sind später in diesem Dokument detailliert aufgeführt. 
---
= Cisco Nexus Switching Betriebsmodi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Verschiedene Cisco Nexus-Produkte können als Switching-Komponente für eine gegebene FlexPod Installation verwendet werden. Die meisten dieser Optionen nutzen die Cisco NX-OS Software. Die Cisco Nexus Switch-Familie bietet innerhalb ihrer Produktlinien unterschiedliche Funktionen. Diese Funktionen sind später in diesem Dokument detailliert aufgeführt.

Ciscos Angebot im Bereich softwaredefinierter Netzwerke heißt Application Centric Infrastructure (ACI). Die Cisco Nexus Produktlinie, die den ACI Modus (Fabric Modus) unterstützt, kann auch im NX-OS Modus eingesetzt werden.

Cisco ACI wurde für die Implementierungen in Datacentern entwickelt, die die Anforderungen einer spezifischen Applikation erfüllen. Applikationen werden durch eine Reihe von Profilen und Verträgen instanziiert, die die Konnektivität vom Host oder der Virtual Machine (VM) über das Netzwerk zum Storage ermöglichen.

FlexPod Datacenter ist mit beiden Betriebsmodi der Cisco Nexus Switches validiert. Weitere Informationen zu den Modi ACI und NX-OS sind auf den folgenden Cisco Seiten verfügbar:

* http://www.cisco.com/c/en/us/solutions/data-center-virtualization/application-centric-infrastructure/index.html["Cisco Application Centric Infrastructure"^]
* https://www.cisco.com/site/us/en/products/networking/cloud-networking/nx-os/index.html["Cisco NX-OS Software"^]

