---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_netapp_ontap.html 
keywords: ontap, aff, asa, fas, afx, system, datacenter, technical, specifications, flexpod, software 
summary: Die NetApp ONTAP Software ist auf jedem NetApp AFF, ASA, FAS und AFX System installiert. FlexPod ist mit ONTAP Software validiert und bietet eine hochskalierbare Speicherarchitektur, die unterbrechungsfreien Betrieb, unterbrechungsfreie Upgrades und eine agile Dateninfrastruktur ermöglicht. 
---
= NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die NetApp ONTAP Software ist das Betriebssystem, das auf AFF, ASA, FAS und AFX Speichersystemen läuft. ONTAP bietet eine hochskalierbare Speicherarchitektur, die unterbrechungsfreie Betriebsabläufe, unterbrechungsfreie Upgrades und eine agile Dateninfrastruktur ermöglicht. Mit dem ONTAP One Lizenzmodell sind alle Enterprise-Datendienste in einem einzigen Paket enthalten, was die Bereitstellung und Verwaltung vereinfacht und gleichzeitig vollen Zugriff auf erweiterte Funktionen bietet. ONTAP bietet robusten Datenschutz durch Technologien wie SnapMirror für Datenreplizierung und Disaster Recovery sowie SnapCenter für applikationskonsistente Sicherung und Wiederherstellung. Es sind zudem integrierte Sicherheitsfunktionen enthalten, darunter Autonomous Ransomware Protection und Verschlüsselung, um Daten vor modernen Bedrohungen zu schützen. Darüber hinaus ermöglicht ONTAP eine nahtlose Integration in Hybrid-Cloud-Umgebungen mit Funktionen wie SnapMirror Cloud und S3-basierter Replizierung, sodass Datenmobilität zwischen lokalen und Cloud-Umgebungen bei gleichzeitiger Wahrung von Konsistenz und Kontrolle möglich ist.

Weitere Informationen zu ONTAP sind auf der  https://www.netapp.com/ontap-data-management-software/["ONTAP Data Management-Software"^] Produktseite verfügbar.
