---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_cisco_components.html 
keywords: cisco, components, ucs, fabric, interconnect, blade, server, rack, apic, nexus, software, support 
summary: Cisco hat entscheidend zum Design und der Architektur von FlexPod beigetragen, die sowohl die Computing- als auch die Netzwerkebenen der Lösung abdeckt. In diesem Abschnitt werden die Optionen von Cisco UCS und Cisco Nexus für FlexPod beschrieben. FlexPod unterstützt sowohl Cisco Server der UCS B-Serie als auch C-Serie. 
---
= Komponenten von Cisco
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cisco hat entscheidend zum Design und der Architektur von FlexPod beigetragen, die sowohl die Computing- als auch die Netzwerkebenen der Lösung abdeckt. In diesem Abschnitt werden die Optionen von Cisco UCS und Cisco Nexus für FlexPod beschrieben. FlexPod unterstützt sowohl Cisco Server der UCS B-Serie als auch C-Serie.



== Cisco UCS Fabric Interconnect-Optionen

In der FlexPod Architektur sind redundante Fabric Interconnects erforderlich. Wenn Sie einem Paar Fabric Interconnects mehrere Cisco UCS Gehäuse hinzufügen, beachten Sie, dass die maximale Anzahl an Gehäusen in einer Umgebung von einer Architektur und einem Port-Limit abhängig ist.

Die in der folgenden Tabelle aufgeführten Teilenummern gelten für die Basis-Fabric-Interconnects. Sie umfassen nicht die Netzteileinheit (PSU), SFP+, QSFP+ oder Erweiterungsmodule. Weitere Fabric Interconnects werden unterstützt, siehe https://mysupport.netapp.com/matrix/["NetApp IMT"^] Für eine komplette Liste.

|===
| Cisco UCS Fabric Interconnect | Teilenummer | Technische Spezifikationen 


| Cisco UCS 6332UP | UCS-FI-6332-UP | http://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/6332-specsheet.pdf["Cisco UCS 6332 Fabric Interconnect"] 


| Cisco UCS 6454 | UCS-FI-6454-U | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/ucs-6454-fab-int-specsheet.pdf["Cisco UCS 6454 Fabric Interconnect"] 
|===


=== Cisco UCS 6454

Die Cisco UCS 6454 Serie bietet verlustfreie, latenzarme 10/25/40/100-GbE-Ethernet- und FCoE-Konnektivität sowie Unified Ports, die einen Ethernet- oder FC-Betrieb ermöglichen. Die 44 10/25-Gbit/s-Ports können als 10-Gbit/s- oder 25-Gbit/s-konvergentes Ethernet betrieben werden. 8 Ports sind einheitliche Ports, die bei FC mit 8/16/32 Gbit/s. betrieben werden können. Vier Ports arbeiten bei 1/10/25 Gbit/s für ältere Konnektivität, und sechs QSFP-Ports dienen als Uplink-Ports mit 40/100 Gbit/s oder Breakout-Ports. Mit NetApp Storage Controllern, die 100-Gbit/s-Adapter unterstützen, können Sie eine vollständige Netzwerkkonnektivität mit 100 Gbit/s herstellen. Informationen zu Adaptern und Plattformunterstützung finden Sie im https://hwu.netapp.com/Adapter/Index["NetApp Hardware Universe"^].

Informationen zu Ports finden Sie im https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/datasheet-c78-741116.html["Cisco UCS 6454 Fabric Interconnect"^] Datenblatt.

Technische Spezifikationen zu den 100-GB-QSFP-Datenmodulen finden Sie im https://www.cisco.com/c/en/us/products/collateral/interfaces-modules/transceiver-modules/datasheet-c78-736282.html["Datenblatt zu Cisco 100GBASE QSFP Modulen"^].



== Cisco UCS B-Series Gehäuse-Option

Zur Verwendung von Cisco UCS B-Series Blades müssen Sie über ein Cisco UCS B-Series Gehäuse verfügen. In der folgenden Tabelle wird die Gehäuseoption Cisco UCS BSeries beschrieben.

|===
| Gehäuse der Cisco UCS B-Serie | Teilenummer | Technische Spezifikationen 


| Cisco UCS 5108 | N20-C6508 | http://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-5100-series-blade-server-chassis/index.html["Blade Server-Chassis der Cisco UCS 5100-Serie"] 
|===
Jedes Cisco UCS 5108 Blade Chassis muss über zwei IOMs der Cisco UCS 2200/2300/2400 Serie verfügen, um redundante Konnektivität zu den Fabric Interconnects bereitzustellen.



== Blade Server-Optionen der Cisco UCS B-Serie

Cisco UCS Blade Server der B-Serie sind in verschiedenen Varianten mit halber Breite und voller Breite verfügbar, wobei verschiedene CPU-, Arbeitsspeicher- und I/O-Optionen verfügbar sind. Die in der folgenden Tabelle aufgeführten Teilenummern beziehen sich auf den Basisserver. Sie enthalten keine CPU, Arbeitsspeicher, Laufwerke oder Mezzanine-Adapterkarten. Es sind mehrere Konfigurationsoptionen verfügbar, die in der FlexPod-Architektur unterstützt werden.

|===
| Cisco UCS Blade der B-Serie | Teilenummer | Technische Spezifikationen 


| CISCO UCS B200 M6 | UCSB-B200-M6 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/datasheet-c78-2368888.html["Cisco UCS B200 M6 Blade Server"] 
|===
Ältere Generationen von Blades der Cisco UCS B-Serie können in der FlexPod Architektur verwendet werden, sofern sie auf dem unterstützt werden https://ucshcltool.cloudapps.cisco.com/public/["Cisco UCS Hardware- und Software-Kompatibilitätsliste"^]. Die Cisco UCS Blade Server der B-Serie müssen zudem über einen gültigen SmartNet-Supportvertrag verfügen.



== Cisco UCS X-Serie: Gehäuseoption

Zur Verwendung der Computing-Nodes der Cisco UCS X-Serie müssen Sie ein Chassis der Cisco UCS X-Serie haben. In der folgenden Tabelle wird die Gehäuseoption des Cisco UCS X-Series beschrieben.

|===
| Cisco UCS X-Serie Blade | Teilenummer | Technische Spezifikationen 


| Cisco UCS 9508 M6 | UCSD-9508 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html["Cisco UCX9508 Gehäuse der X-Serie"] 
|===
Jedes Cisco UCS 9508 Chassis muss über zwei Cisco UCS 9108 Intelligent Fabric Modules (IFMS) verfügen, um redundante Konnektivität zu den Fabric Interconnects bereitzustellen.



== Optionen für Cisco UCS X-Series Geräte

Cisco UCS X-Series Computing-Nodes stehen mit unterschiedlichen CPU-, Speicher- und I/O-Optionen zur Verfügung. Die in der folgenden Tabelle aufgeführten Teilenummern gelten für den Basis-Node. Sie enthalten keine CPU, Arbeitsspeicher, Laufwerke oder Mezzanine-Adapterkarten. Es sind mehrere Konfigurationsoptionen verfügbar, die in der FlexPod-Architektur unterstützt werden.

|===
| Cisco UCS X-Serie Computing-Nodes | Teilenummer | Technische Spezifikationen 


| Cisco UCS X210c M6 | UCSD-210C-M6 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2465523.html?ccid=cc002456&oid=dstcsm026318["Cisco UCS X210c M6 Computing-Node"] 
|===


== Rack Server-Optionen für Cisco UCS C-Serie

Cisco UCS C-Series Rack Server sind in einer und zwei Höheneinheiten (HE) erhältlich und bieten verschiedene CPU-, Arbeitsspeicher- und I/O-Optionen. Die Teilenummern, die in der zweiten Tabelle unten aufgeführt sind, beziehen sich auf den Basisserver. Sie umfassen keine CPUs, Arbeitsspeicher, Laufwerke, PCIe-Karten (Peripheral Component Interconnect Express) oder den Cisco Fabric Extender. Es sind mehrere Konfigurationsoptionen verfügbar, die in der FlexPod-Architektur unterstützt werden.

In der folgenden Tabelle werden die Optionen für Cisco UCS Rack Server der C-Serie aufgeführt.

|===
| Rack Server der Cisco UCS C-Serie | Teilenummer | Technische Spezifikationen 


| CISCO UCS C220 M6 | UCSC-C220-M6 | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/c220m6-sff-specsheet.pdf["Cisco UCS C220 M6 Rack Server"] 


| CISCO UCS C225 M6 | UCSC-C225-M6 | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/c225-m6-sff-specsheet.pdf["Cisco UCS C225 M6 Rack Server"] 


| CISCO UCS C240 M6 | UCSC-C240-M6 | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/c240m6-sff-specsheet.pdf["Cisco UCS C240 M6 Rack Server"] 


| CISCO UCS C245 M6 | UCSC-C245-M6 | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/c245m6-sff-specsheet.pdf["Cisco UCS C245 M6 Rack Server"] 
|===
Ältere Generationen von Cisco UCS C-Series Servern können in der FlexPod Architektur verwendet werden, sofern sie auf der unterstützt werden https://ucshcltool.cloudapps.cisco.com/public/["Cisco UCS Hardware- und Software-Kompatibilitätsliste"^]. Die Cisco Server der UCS C-Serie müssen zudem über einen gültigen SmartNet-Supportvertrag verfügen.



== Switch-Optionen für die Cisco Nexus 5000 Serie

In der FlexPod Architektur sind redundante Switches der Cisco Nexus 5000, 7000 oder 9000 Serie erforderlich. Die in der nachstehenden Tabelle aufgeführten Teilenummern gelten für die Gehäuse der Cisco Nexus 5000 Serie. Dabei sind keine SFP-Module, kein Add-on FC- oder Ethernet-Module enthalten.

|===
| Switch der Cisco Nexus 5000-Serie | Teilenummer | Technische Spezifikationen 


| Cisco Nexus 56128P | N5K-C56128P .2+| http://www.cisco.com/c/en/us/products/collateral/switches/nexus-5000-series-switches/datasheet-c78-730760.html["Switches Der Cisco Nexus 5600 Plattform"] 


| Cisco Nexus 5672UP-16G | N5K-C5672UP-16G 


| Cisco Nexus 5596UP | N5K-C5596UP-FA .2+| http://www.cisco.com/c/en/us/products/collateral/switches/nexus-5000-series-switches/data_sheet_c78-618603.html["Cisco Nexus 5548 und 5596 Switches"] 


| Cisco Nexus 5548UP | N5K-C5548UP-FA 
|===


== Switch-Optionen für die Cisco Nexus 7000 Serie

In der FlexPod Architektur sind redundante Switches der Cisco Nexus 5000, 7000 oder 9000 Serie erforderlich. Die in der nachstehenden Tabelle aufgeführten Teilenummern gelten für die Gehäuse der Cisco Nexus 7000 Serie. SFP-Module, Line Cards und Netzteile sind nicht enthalten, aber Lüftereinschübe.

|===
| Switch Der Cisco Nexus 7000-Serie | Teilenummer | Technische Spezifikationen 


| Cisco Nexus 7004 | N7K-C7004 | http://www.cisco.com/en/US/products/ps12735/index.html["Cisco Nexus Switch Mit 7000 4 Steckplätzen"] 


| Cisco Nexus 7009 | N7K-C7009 | http://www.cisco.com/en/US/products/ps11565/index.html["Cisco Nexus Switch Mit 7000 9 Steckplätzen"] 


| Cisco Nexus 7702 | N7K-C7702 | http://www.cisco.com/c/en/us/products/switches/nexus-7700-2-slot-switch/index.html["Cisco Nexus 7700 Switch Mit 2 Steckplätzen"] 


| Cisco Nexus 7706 | N77-C7706 | http://www.cisco.com/en/US/products/ps13482/index.html["Cisco Nexus Switch Mit 7700 6 Steckplätzen"] 
|===


== Switch-Optionen für die Cisco Nexus 9000 Serie

In der FlexPod Architektur sind redundante Switches der Cisco Nexus 5000, 7000 oder 9000 Serie erforderlich. Die in der unten stehenden Tabelle aufgeführten Teilenummern gelten für Gehäuse der Cisco Nexus 9000 Serie. SFP-Module und Ethernet-Module sind nicht enthalten.

|===
| Switch Der Cisco Nexus 9000-Serie | Teilenummer | Technische Spezifikationen 


| Cisco Nexus 93180YC-FX | N9K-C93180YC-FX .5+| http://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-729405.html["Switches Der Cisco Nexus 9300-Serie"] 


| Cisco Nexus 93180YC-EX | N9K-93180YC-EX 


| Cisco Nexus 9336PQ ACI Wirbelsäule | N9K-C9336PQ 


| Cisco Nexus 9332PQ | N9K-C9332PQ 


| Cisco Nexus 9336C-FX2 | N9K-C9336C-FX2 


| Cisco Nexus 92304QC | N9K-C92304QC .2+| http://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html["Switches Der Cisco Nexus 9200-Serie"] 


| Cisco Nexus 9236C | N9K-9236C 
|===

NOTE: Einige Switches der Cisco Nexus 9000-Serie verfügen über zusätzliche Varianten. Diese Varianten werden im Rahmen der FlexPod Lösung unterstützt. Die vollständige Liste der Switches der Cisco Nexus 9000-Serie finden Sie unter http://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/tsd-products-support-series-home.html["Switches Der Cisco Nexus 9000-Serie"^] Auf der Cisco Website zu finden.



== Cisco APIC-Optionen

Bei der Implementierung von Cisco ACI müssen zusätzlich zu den Elementen im Abschnitt die drei Cisco APICs konfiguriert werden link:dc-tech-spec_technical_specifications_and_references.html#cisco-nexus-9000-series-switches["Switches Der Cisco Nexus 9000-Serie"]. Weitere Informationen zu den Cisco APIC-Größen finden Sie im http://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/application-policy-infrastructure-controller-apic/datasheet-c78-732414.html["Datenblatt Zu Cisco Application Centric Infrastructure."^]

Weitere Informationen zu APIC-Produktspezifikationen finden Sie in Tabelle 1 bis Tabelle 3 auf der https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/application-policy-infrastructure-controller-apic/datasheet-c78-739715.html["Datenblatt Zum Cisco Application Policy Infrastructure Controller"^].



== Cisco Nexus Fabric Extender Optionen

Für große FlexPod-Architekturen, die Server der C-Serie nutzen, werden redundante rackmontierte FEXs der Cisco Nexus 2000-Serie empfohlen. In der folgenden Tabelle werden einige Cisco Nexus FEX-Optionen beschrieben. Alternative FEX-Modelle werden ebenfalls unterstützt. Weitere Informationen finden Sie im https://ucshcltool.cloudapps.cisco.com/public/["Cisco UCS Hardware- und Software-Kompatibilitätsliste"^].

|===
| Cisco Nexus rackmontierter FEX | Teilenummer | Technische Spezifikationen 


| Cisco Nexus 2232PP | N2K-C2232PP .2+| http://www.cisco.com/en/US/prod/collateral/switches/ps9441/ps10110/data_sheet_c78-507093.html["Cisco Nexus 2000 Series Fabric Extender"] 


| Cisco Nexus 2232TM-E | N2K-C2232TM-E 


| Cisco Nexus 2348UPQ | N2K-C2348UPQ .2+| http://www.cisco.com/c/en/us/products/collateral/switches/nexus-2000-series-fabric-extenders/datasheet-c78-731663.html["Cisco Nexus 2300 Platform Fabric Extender"] 


| Cisco Nexus 2348TQCisco Nexus 2348TQ-E | N2K-C2348TQN2K-C2348TQ-E 
|===


== Cisco MDS Optionen

Cisco MDS Switches sind optionale Komponente in der FlexPod Architektur. Bei der Implementierung des Cisco MDS Switches für FC SAN sind redundante SAN Switch Fabrics erforderlich. In der folgenden Tabelle sind die Teilenummern und Details für einen Teil der unterstützten Cisco MDS-Switches aufgeführt. Siehe https://mysupport.netapp.com/matrix/["NetApp IMT"^] Und https://ucshcltool.cloudapps.cisco.com/public/["Cisco Hardware- und Software-Kompatibilitätsliste"^] Erhalten Sie eine vollständige Liste der unterstützten SAN Switches.

|===
| Switch der Cisco MDS 9000 Serie | Teilenummer | Beschreibung 


| Cisco MDS 9148T | DS-C9148T-24IK .2+| http://www.cisco.com/c/en/us/products/storage-networking/mds-9100-series-multilayer-fabric-switches/models-listing.html["Switches der Cisco MDS 9100 Serie"] 


| Cisco MDS 9132T | DS-C9132T-MEK9 


| Cisco MDS 9396S | DS-C9396S-K9 | http://www.cisco.com/c/en/us/products/storage-networking/mds-9396s-16g-multilayer-fabric-switch/index.html["Switches der Cisco MDS 9300 Serie"] 
|===


== Cisco Software-Lizenzoptionen

Für die Aktivierung von Storage-Protokollen auf den Cisco Nexus Switches sind Lizenzen erforderlich. Die Switches der Cisco Nexus Serien 5000 und 7000 erfordern alle eine Storage-Services-Lizenz, um das FC- oder FCoE-Protokoll für SAN-Boot-Implementierungen zu aktivieren. Die Switches der Cisco Nexus 9000 Serie unterstützen momentan keine FC oder FCoE.

Die erforderlichen Lizenzen und die Teilenummern dieser Lizenzen variieren je nach den Optionen für die jeweilige Komponente der FlexPod Lösung. Beispielsweise variieren die Teilenummern für Softwarelizenzen je nach Anzahl der Ports und den Switches der Cisco Nexus 5000- oder 7000-Serie. Genaue Teilenummern können von Ihrem Vertriebsmitarbeiter angegeben werden. In der folgenden Tabelle sind die Cisco Software-Lizenzoptionen aufgeführt.

|===
| Cisco Softwarelizenzen | Teilenummer | Lizenzinformationen 


| Cisco Nexus 5500 Storage-Lizenz für 8, 48 und 96 Ports | N55-8P-SSK9/N55-48P-SSK9/N55-96P-SSK9 .5+| http://www.cisco.com/c/en/us/td/docs/switches/datacenter/sw/nx-os/licensing/guide/b_Cisco_NX-OS_Licensing_Guide/b_Cisco_NX-OS_Licensing_Guide_chapter_01.html["Lizenzierung der Cisco NX-OS-Softwarefunktionen"] 


| Lizenz Für Cisco Nexus 5010/5020 Storage-Protokolle | N5010-SSK9/N5020-SSK9 


| Lizenz Für Cisco Nexus 5600 Storage-Protokolle | N56-16P-SSK9/N5672-72P-SSK9/N56128-128P-SSK9 


| Cisco Nexus 7000 Storage Enterprise-Lizenz | N7K-SAN1K9 


| Cisco Nexus 9000 Enterprise Services-Lizenz | N95-LAN1K9/N93-LAN1K9 
|===


== Cisco Support-Lizenzoptionen

Für alle Cisco Geräte in der FlexPod Architektur sind gültige SmartNet Support-Verträge erforderlich.

Die erforderlichen Lizenzen und die Teilenummern für diese Lizenzen müssen von Ihrem Vertriebsvertreter überprüft werden, da diese für verschiedene Produkte variieren können. In der folgenden Tabelle sind die Lizenzoptionen für den Cisco Support aufgeführt.

|===
| Cisco Support-Lizenzierung | Lizenzhandbuch 


| Smart Net Total Care Vor Ort Premium | http://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/smart-net-total-care/datasheet-c78-735459.pdf["Cisco Smart Net Total Care Service"] 
|===