---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_solution_overview.html 
keywords: flexpod, datacenter, technical specifications, platform, architecture 
summary: 'Die FlexPod Plattform ist eine vorkonfigurierte, nach Best Practices entwickelte Rechenzentrumsarchitektur, die auf dem Cisco Unified Computing System (Cisco UCS), der Cisco Nexus Familie von Switches und NetApp Storage Controllern (NetApp AFF, ASA, FAS oder AFX Systemen) basiert.' 
---
= Technische Spezifikationen für FlexPod Datacenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die FlexPod Plattform ist eine vorkonfigurierte, nach Best Practices entwickelte Rechenzentrumsarchitektur, die auf dem Cisco Unified Computing System (Cisco UCS), der Cisco Nexus und MDS (für FC) Familie von Switches sowie NetApp Storage Controllern (AFF, ASA, FAS oder AFX Systeme) basiert.

FlexPod ist eine geeignete Plattform für den Betrieb einer Vielzahl von Virtualisierungshypervisoren, Bare-Metal-Betriebssystemen, containerisierten Umgebungen und Enterprise-Workloads. FlexPod bietet nicht nur eine Basiskonfiguration, sondern auch die Flexibilität, um für viele verschiedene Anwendungsfälle und Anforderungen dimensioniert und optimiert zu werden.


NOTE: Bevor Sie eine komplette FlexPod Konfiguration bestellen, siehe  http://www.netapp.com/us/technology/flexpod["NetApp FlexPod Homepage"^] die neueste Version dieser technischen Spezifikationen.

link:dc-tech-spec_flexpod_platforms.html["Als Nächstes: FlexPod Plattformen."]
