---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, switches, fabric, interconnects, servers, storage, controllers 
summary: Eine FlexPod Datacenter Konfiguration verfügt über ein Minimum an Hardware-Anforderungen, einschließlich Switches, Fabric Interconnects, Servern und NetApp Storage Controllern. 
---
= Mindestanforderungen an die Hardware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Eine FlexPod Datacenter Konfiguration verfügt über ein Minimum an Hardware-Anforderungen, einschließlich Switches, Fabric Interconnects, Servern und NetApp Storage Controllern.

Eine FlexPod-Konfiguration umfasst die folgenden Mindestanforderungen an die Hardware:

* Zwei Cisco Nexus Switches in redundanter Konfiguration. Diese Konfiguration kann aus zwei redundanten Switches der zuvor erwähnten Cisco Nexus 9000 Serie bestehen. Die beiden Switches sollten vom gleichen Modell sein und im gleichen Betriebsmodus konfiguriert werden.



NOTE: Bei der Bereitstellung einer ACI-Architektur sind die folgenden zusätzlichen Anforderungen zu berücksichtigen: * Die Cisco Nexus 9000 Series Switches sind in einer Leaf-Spine-Topologie bereitzustellen. * Drei Cisco Application Policy Infrastructure Controller (APICs) sind zu verwenden.

* Zwei Cisco UCS 6400, 6500 oder 6600 Series Fabric Interconnects in redundanter Konfiguration, wenn die UCS C-Series Rack Server oder die X-Series Modular systems verwendet werden.
* Zwei Cisco UCS C-Series Rack-Server mit FI-Konnektivität und Intersight-verwalteter Konfiguration (IMM), oder Cisco UCS X-Series Direct mit Cisco IMM, oder Cisco UCS X-Series Modular mit Cisco Intersight-verwalteter Konfiguration (IMM).



NOTE: Wenn Sie die UCS Rackserver ohne FI-Konnektivität verwenden, können Sie CIMC oder den Intersight Standalone-Modus für das Management verwenden.

* Zwei NetApp AFF, NetApp ASA oder NetApp FAS Controller in einer hochverfügbaren (HA) Paar-Konfiguration, bereitgestellt als Zwei-Node-Cluster. Bei Verwendung von NetApp AFX sind mindestens vier NetApp AFX Controller erforderlich, die zusammen mit einem Paar Cluster-Interconnect-Switches als Vier-Node-HA-Cluster bereitgestellt werden.
* Für Storage-Controller, die kein integriertes Disk-Shelf besitzen, ist mindestens ein NetApp Disk-Shelf erforderlich.

