---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_minimum_software_requirements.html 
keywords: minimum, software, requirements, flexpod, express, aff, fas, e, series 
summary: In diesem Abschnitt werden die Mindestanforderungen für Software für die verschiedenen Versionen von FlexPod Express beschrieben. 
---
= Mindestanforderungen An Die Software
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In diesem Abschnitt werden die Mindestanforderungen für Software für die verschiedenen Versionen von FlexPod Express beschrieben.



== Softwarevoraussetzungen für FlexPod Express mit NetApp AFF/ ASA/ FAS

Die Softwarevoraussetzungen für die FlexPod Express mit NetApp AFF/ ASA/ FAS umfassen:

* ONTAP 9.16 oder höher
* Cisco NX-OS Version 10.4(6)M oder höher



NOTE: Alle in diesem Abschnitt aufgeführten Softwareversionen stellen die Mindestanforderungen für die Hardwarekomponenten (NetApp und Cisco-Komponenten) dar, die in den nachfolgenden Abschnitten des Dokuments aufgeführt sind.

Alle Software muss in aufgeführt und unterstützt sein http://support.netapp.com/matrix/["NetApp IMT"^]. Bestimmte Softwarefunktionen erfordern möglicherweise mehr aktuelle Code-Versionen als die in vorherigen Architekturen aufgeführten Mindestwerte.
