---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: NetApp Speichercontroller bilden die Speichergrundlage in der FlexPod Express-Architektur für die Speicherung von System- und Anwendungsdaten. Dieser Abschnitt listet die verschiedenen NetApp Speicheroptionen in der FlexPod Express-Architektur auf. 
---
= Komponenten von NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp Storage-Controller bilden die Storage-Grundlage in der FlexPod Express Architektur für Boot- und Applikationsdaten. In diesem Abschnitt werden die verschiedenen NetApp Optionen in der Architektur von FlexPod Express aufgeführt.



[[netapp-storage-controller-options]]
== Optionen für NetApp Storage Controller

Redundante Controller der Serien AFF, ASA oder FAS sind in der FlexPod Express-Architektur erforderlich. Die Controller führen die ONTAP-Software aus. Bei der Bestellung der Speichercontroller kann die bevorzugte Softwareversion auf den Controllern vorinstalliert werden. Für ONTAP kann das Cluster entweder mit einem Paar Cluster-Interconnect-Switches oder in einer Cluster ohne Switches-Konfiguration bereitgestellt werden.


NOTE: Eine Cluster ohne Switches Konfiguration wird nur für eine Zwei-Knoten-Konfiguration unterstützt. Cluster Interconnect Switches sind für Konfigurationen mit vier oder mehr Knoten erforderlich und für eine Zwei-Knoten-Konfiguration optional.

Je nach gewählter Speicherplattform stehen verschiedene Optionen und Konfigurationen zur Verfügung. Für Details zu diesen zusätzlichen Komponenten wenden Sie sich bitte an Ihren Vertriebsmitarbeiter.

Die in der folgenden Tabelle aufgeführten Controller-Familien eignen sich für den Einsatz in einer FlexPod-Lösung, da ihre Anbindung an die Cisco Nexus Switches nahtlos erfolgt. Siehe die http://hwu.netapp.com/["NetApp Hardware Universe"^]für spezifische Kompatibilitätsdetails zu den einzelnen Controller-Modellen.

|===
| NetApp Einstiegs-Speicherfamilie für FlexPod Express | Modell | Technische Spezifikationen 


.2+| AFF A-Serie | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["AFF A-Series - Dokumentation"] 


| A30 


| AFF C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["AFF C-Series-Dokumentation"] 


.2+| ASA A-Series | A20 .3+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA-Dokumentation"] 


| A30 


| ASA C-Series | C30 


.3+| FAS | FAS 2750 .3+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS-Dokumentation"] 


| FAS 2820 


| FAS 50 
|===


[[netapp-disk-shelves-and-disks]]
== NetApp Platten-Shelves und Festplatten

Für Storage-Controller, die kein integriertes Disk-Shelf besitzen, ist mindestens ein NetApp Disk-Shelf erforderlich. Der ausgewählte NetApp Shelf-Typ bestimmt, welche Laufwerkstypen in diesem Shelf verfügbar sind.


NOTE: Alle Festplatten-Shelfs und Festplatten-Teilenummern können bei Ihrem Vertriebsmitarbeiter angegeben werden.

Die folgende Tabelle listet die NetApp Festplattengehäuseoptionen für FlexPod Express zusammen mit Links zu den technischen Spezifikationen auf.

Um die Liste der für Ihr Disk-Shelf unterstützten Laufwerke zu erhalten, gehen Sie zu link:https://hwu.netapp.com/DetailViews/Home.aspx["NetApp Hardware Universe"^], wählen Sie unter *Products > Storage > Shelves* *ONTAP (AFF, ASA, FAS)* aus, wählen Sie die von Ihnen verwendete ONTAP-Version, dann den Shelf-Typ (zum Beispiel: *DS212C*) und klicken Sie auf *Show Results*. Mit einem Klick auf *Supported Drives* werden die für bestimmte Versionen von ONTAP und die Disk-Shelfs unterstützten Laufwerke angezeigt.

|===
| Festplatten-Shelf | Technische Spezifikationen 


| DS212C .5+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["Festplattengehäuse und Speichermedien"] 


| DS224C 


| DS460C 


| NS224 


| NS224 mit NSM100B 
|===


[[netapp-software-licensing-options]]
== NetApp Software-Lizenzoptionen

Die folgende Tabelle listet die NetApp Softwarelizenzierungsoptionen auf.

|===
| NetApp Softwarelizenzierung | Technische Spezifikationen 


| ONTAP One für AFF und FAS .2+| Wenden Sie sich an Ihr NetApp Vertriebsteam, um weitere Lizenzierungsinformationen zu erhalten. 


| ONTAP One für SAN für ASA 
|===
Unter diesem Link sind weitere Informationen zur NetApp Softwarelizenzierung verfügbar: https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["NetApp Softwarelizenzierung"^].



[[netapp-support-licensing-options]]
== NetApp Support – Lizenzoptionen

Die SupportEdge Premium Lizenzen sind erforderlich. Die Teilenummern dieser Lizenzen variieren je nach den im FlexPod Express Design ausgewählten Optionen.

Die folgende Tabelle listet die NetApp Support-Lizenzierungsoptionen für NetApp AFF, ASA und FAS Storage-Systeme auf.

|===
| Lizenzierung des NetApp Supports | Technische Spezifikationen 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===