---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, express, cisco, ucs, cabling 
summary: In diesem Abschnitt werden die Stromanforderungen und die Verkabelungsrichtlinien für die Festplattengehäuse eines FlexPod Express Designs beschrieben. 
---
= Richtlinien für Stromversorgung und Verkabelung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In diesem Abschnitt werden die Stromversorgungsanforderungen und Verkabelungsrichtlinien für ein FlexPod Express Design beschrieben.



[[power-requirements]]
== Stromversorgung

Die Stromanforderungen für FlexPod Express unterscheiden sich je nach Standort, an dem die FlexPod Express Konfiguration installiert ist.

Weitere Daten zur maximal benötigten Leistung und detaillierte Informationen zur Leistungsaufnahme sind in der link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_technical_specifications_and_references.html["technische Spezifikationen"^] für jede Hardwarekomponente zu finden.

Detaillierte Informationen zur Stromversorgung von Cisco UCS finden Sie im http://www.cisco.com/assets/cdc_content_elements/flash/dataCenter/cisco_ucs_power_calculator/["Cisco UCS – Stromversorgungsrechner"^].

Für NetApp-Stromversorgungsdaten von Speichercontrollern siehe  http://hwu.netapp.com/Controller/Index?platformTypeId=6780858["NetApp Hardware Universe"^]. Unter *Plattformen* die gewünschte Speicherplattform (zum Beispiel AFF A20) und die ONTAP-Version auswählen und anschließend auf *Ergebnisse anzeigen* klicken. Netzkabeldaten sind im Abschnitt *Unterstützte Netzkabel* aufgeführt. Einzelheiten zu Größe, Gewicht, Wattzahl usw. finden sich im Abschnitt *Größe, Gewicht, Geräuschentwicklung, Stromversorgung*.



[[cabling-guidelines]]
== Verkabelungsrichtlinien

Dieser Abschnitt enthält allgemeine Verkabelungsrichtlinien für ein FlexPod Express Design.

* Redundante Konnektivität für die Compute- und Storage-Verbindungen sicherstellen.
* Die Geschwindigkeit der Verbindungen muss mit den angeschlossenen Komponenten kompatibel sein.
* Im Abschnitt link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_express_topologies.html["FlexPod Express-Topologien"^] sind zusätzliche Verkabelungsrichtlinien für spezifische Topologien aufgeführt.


Die folgende Tabelle enthält Verkabelungsrichtlinien für NetApp Festplattengehäuse, die in einem FlexPod Express Design verwendet werden können.

|===


| Festplatten-Shelf | Verkabelungsrichtlinien 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["SAS-Verkabelungsregeln"^] 


| DS224C 


| DS460C 


| NS224 .2+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["NS224 Shelf-Anforderungen und Best Practices"^] 


| NS224 mit NSM100B 
|===