---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, fas, cimc, configuration, rack, servers, ucs 
summary: In diesem Abschnitt werden die Mindestanforderungen an die Hardware für die verschiedenen Versionen von FlexPod Express beschrieben. 
---
= Mindestanforderungen an die Hardware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In diesem Abschnitt werden die Mindestanforderungen an die Hardware für die verschiedenen Versionen von FlexPod Express beschrieben.



== FlexPod Express mit NetApp FAS

Die Hardwareanforderungen für FlexPod Express-Lösungen, die NetApp FAS Controller für den zugrunde liegenden Speicher verwenden, umfassen die in diesem Abschnitt beschriebenen Konfigurationen.



=== CIMC-basierte Konfiguration (eigenständige Rack-Server)

Die Konfiguration des Cisco Integrated Management Controller (CIMC) umfasst die folgenden Hardwarekomponenten:

* Zwei 10-Gbit/s-Standard-Ethernet-Switches in redundanter Konfiguration (Cisco Nexus 31108 wird empfohlen, mit Unterstützung für Cisco Nexus 3000 und 9000 Modelle)
* Cisco UCS C-Series Standalone-Rackserver
* Zwei AFF C190, AFF A250, FAS2600 oder FAS 2700 Controller in einer Hochverfügbarkeits-(HA)-Paarkonfiguration, die als Zwei-Node-Cluster bereitgestellt wird




=== Cisco UCS-verwaltete Konfiguration

Die Cisco UCS-verwaltete Bestätigung umfasst die folgenden Hardwarekomponenten:

* Zwei 10-Gbit/s-Standard-Ethernet-Switches in redundanter Konfiguration (Cisco Nexus 3524 wird empfohlen)
* Ein Cisco UCS 5108 Wechselstrom-Blade-Server-Chassis
* Zwei Cisco UCS 6324 Fabric Interconnects
* Cisco UCS B-Series Server (mindestens vier Cisco UCS B200 M5 Blade-Server)
* Zwei AFF C190, AFF A250, FAS2750 oder FAS2720 Controller in einer HA-Paarkonfiguration (erfordert zwei verfügbare Zieladapter 2 [UTA2] Ports pro Controller)




== FlexPod Express mit E-Serie

Die Hardwarevoraussetzungen für die FlexPod Express-Konfiguration mit E-Series-Starter umfassen:

* Zwei Cisco UCS 6324 Fabric Interconnects
* Ein Cisco UCS Mini-Chassis 5108 AC2 oder DC2 (die Cisco UCS 6324 fabric interconnects werden nur im AC2- und DC2-Chassis unterstützt)
* Cisco UCS B-Series Server (mindestens zwei Cisco UCS B200 M4 Blade-Server)
* Eine HA-Paarkonfiguration eines E-Series E2824-Speichersystems mit mindestens 12 Festplattenlaufwerken
* Zwei 10-Gbit/s-Standard-Ethernet-Switches in redundanter Konfiguration (vorhandene Switches im Rechenzentrum können verwendet werden)


Diese Hardwarekomponenten werden für die Einrichtung einer Starterkonfiguration der Lösung benötigt; zusätzliche Blade-Server und Festplatten können bei Bedarf hinzugefügt werden. Das Speichersystem E-Series E2824 kann durch eine höhere Plattform ersetzt und auch als All-Flash-System betrieben werden.
