---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_technical_specifications_and_references.html 
keywords: technical, specifications, references, servers, ucs, rack, disk, shelves, aff, asa, fas, x-series-direct, c-series, adapters, controllers 
summary: In diesem Abschnitt werden zusätzliche, wichtige technische Spezifikationen für jede der FlexPod Express Komponenten beschrieben. 
---
= Technische Spezifikationen und Referenzen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In diesem Abschnitt werden zusätzliche, wichtige technische Spezifikationen für jede der FlexPod Express Komponenten beschrieben.



[[cisco-ucs-x-series-direct-chassis]]
== Cisco UCS X-Series Direct Chassis

Die technischen Spezifikationen für Cisco UCS X-Series Direct Chassis, wie in der folgenden Tabelle dargestellt, umfassen die folgenden Komponenten:

* Anzahl der Höheneinheiten
* Maximale Anzahl an Nodes
* Unified Fabric Funktionalität
* Anzahl der I/O-Einschübe für IFMS


|===
| Komponente | Cisco UCS X9508 Chassis 


| Höheneinheiten | 7 


| Maximale Anzahl an Nodes | 8 


| Der sogenannten Unified Fabric | Ja. 


| I/O-Einschübe für IFMS | Zwei Einschübe für Cisco UCS 9108 Intelligent Fabric Module (IFMS) 
|===
Weitere Informationen finden Sie im link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html["Datenblatt zum Cisco UCS X9508 X-Series Gehäuse"^].



[[cisco-ucs-x-series-direct-compute-node]]
== Cisco UCS X-Series Direct Compute Node

Die technischen Spezifikationen für Cisco UCS X-Series Compute Node umfassen die folgenden Komponenten:

* Anzahl der Prozessorsockeln
* Prozessorunterstützung
* Speicherkapazität
* Größe und Geschwindigkeit
* SAN Boot-Unterstützung
* Anzahl der Mezzanine-Adaptersteckplätze
* Maximaler I/O-Durchsatz
* Formfaktor
* Maximale Anzahl der Computing-Nodes pro Chassis


Die technischen Spezifikationen für Cisco UCS X-Series Direct Compute-Knoten sind in der folgenden Tabelle aufgeführt.

|===


| Komponente | Cisco UCS Datenblatt 


| Cisco UCS X210c M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html["Cisco UCS X210c M7 Compute Node"] 


| Cisco UCS X210c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html["Cisco UCS X210c M8 Compute Node"] 


| Cisco UCS X215c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html["Cisco UCS X215c M8 Compute Node"] 


| Cisco UCS X410c M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html["Cisco UCS X410c M7 Compute Node"] 


| Cisco UCS X410c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html["Cisco UCS X410c M8 Compute Node"] 
|===


[[cisco-ucs-x-series-direct-fabric-interconnect]]
== Cisco UCS X-Series Direct Fabric Interconnect

Die technischen Spezifikationen für Cisco UCS X-Series Direct Fabric Interconnect umfassen Formfaktor, Gesamtzahl der Ports und Erweiterungssteckplätze sowie Durchsatzkapazität. In der folgenden Tabelle finden Sie das Cisco UCS X-Series Direct Fabric Interconnect Datenblatt.

|===
| Komponente | Cisco UCS Datenblatt 


| Cisco UCS 9108 100G Fabric Interconnect | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf["Cisco UCS 9108 100G Fabric Interconnect"] 
|===


[[cisco-ucs-xe9305-chassis-cisco-unified-edge]]
== Cisco UCS XE9305 Chassis (Cisco Unified Edge)

Die technischen Spezifikationen für Cisco UCS XE9305 Chassis, wie in der folgenden Tabelle dargestellt, umfassen die folgenden Komponenten:

|===
| Komponente | Cisco UCS XE9305 Chassis 


| Höheneinheiten | 3 


| Maximale Anzahl an Nodes | 5 Cisco UCS XE130c M8 Compute Nodes oder 2 Cisco UCS XE150c M8 Compute Nodes 
|===
Weitere Informationen sind in der link:https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe9305-m8-chassis-spec-sheet.pdf["Cisco UCS XE9305 Chassis Datenblatt"^] zu finden.



[[cisco-ucs-compute-nodes-for-cisco-unified-edge]]
== Cisco UCS Compute Nodes für Cisco Unified Edge

Die technischen Spezifikationen für Cisco UCS Compute Nodes für Cisco Unified Edge umfassen die folgenden Komponenten:

* Anzahl der Prozessorsockeln
* Prozessorunterstützung
* GPU-Unterstützung
* Speicherkapazität
* Größe und Geschwindigkeit
* Maximaler I/O-Durchsatz
* Formfaktor


Die Rechenknoten unterstützen ebenfalls GPUs, der XE130c M8 unterstützt NVIDIA L4 GPU und der XE150c M8 unterstützt NVIDIA RTX PRO 4500 / 6000 Blackwell Server Edition GPUs. Die technischen Spezifikationen für Cisco UCS Unified Edge Rechenknoten sind in der folgenden Tabelle aufgeführt.

|===


| Komponente | Cisco UCS Datenblatt 


| Cisco UCS XE130c M8 Compute Node | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe130c-m8-compute-node-spec-sheet.pdf["Cisco UCS XE130c M8 Compute Node"] 


| Cisco UCS XE150c M8 Compute Node | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/unified-edge/cisco-ucs-xe150c-m8-compute-node.pdf["Cisco UCS XE150c M8 Compute Node"] 
|===
Weitere Einzelheiten sind unter link:https://www.cisco.com/c/en/us/products/servers-unified-computing/unified-edge/datasheet-listing.html["Cisco Unified Edge Datenblattliste"^] zu finden.



[[cisco-ucs-c-series-rack-servers]]
== Rack-Server der Cisco UCS C-Serie

Die technischen Spezifikationen der Cisco UCS C-Series Rack-Server umfassen Prozessorunterstützung, maximale Speicherkapazität, Anzahl der PCIe-Steckplätze und Formfaktor. Weitere Details zu kompatiblen UCS-Servermodellen sind in der  https://ucshcltool.cloudapps.cisco.com/public/["Cisco Hardware-Kompatibilität"^] Liste zu finden.

Die technischen Spezifikationen für Cisco UCS C-Series Rack Server sind in der folgenden Tabelle aufgeführt.

|===
| Komponente | Cisco UCS Datenblatt 


| Cisco UCS C220 M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html["Cisco UCS C220 M7 Rack Server"] 


| Cisco UCS C220 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html["Cisco UCS C220 M8 Rack Server"] 


| CISCO UCS C225 M6 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m6-sff-rack-server-ds.html["Cisco UCS C225 M6 Rack Server"] 


| Cisco UCS C240 M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html["Cisco UCS C240 M7 Rack Server"] 


| Cisco UCS C240 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html["Cisco UCS C240 M8 Rack Server"] 


| CISCO UCS C245 M6 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m6-sff-rack-server-ds.html["Cisco UCS C245 M6 Rack Server"] 


| Cisco UCS C245 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html["Cisco UCS C245 M8 Rack Server"] 
|===


[[cisco-nexus-switches]]
== Cisco Nexus Switches

Die technischen Spezifikationen für Cisco Nexus Switches sind im Datenblatt für jedes Modell enthalten. Zu den Spezifikationen gehören die Formfaktorgröße, die Anzahl der Supervisor-, Fabric-Modul- und Linecard-Steckplätze sowie die maximale Anzahl der Ports. Diese Datenblätter sind in der folgenden Tabelle zu finden.

|===
| Komponente | Cisco Nexus Datenblatt 


| Cisco Nexus 9200 Serie | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html["Switches Der Cisco Nexus 9200-Serie"] 


| Cisco Nexus 9300 Serie | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["Switches Der Cisco Nexus 9300-Serie"] 
|===


[[netapp-storage-controllers]]
== NetApp Storage Controller

Zu den technischen Spezifikationen für NetApp Storage-Controller gehören die Plattformkonfiguration, die maximale Bruttokapazität, der Speicher, der Formfaktor, die ONTAP Versionserfordernisse, die Festplattengehäuse usw.



[[netapp-aff-a-series]]
=== NetApp AFF A-Series

Einstiegsmodelle NetApp AFF A-Series Speichercontroller werden für die Verwendung in FlexPod Express unterstützt. Weitere Informationen sind im https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Technische Spezifikationen der AFF A-Serie"^] Datenblatt und in der https://hwu.netapp.com/["NetApp Hardware Universe"^] verfügbar. Detaillierte Informationen zu einem bestimmten AFF Modell sind in der plattformspezifischen Dokumentation in der folgenden Tabelle zu finden.

|===
| Komponente | Dokumentation der Controller-Plattform der AFF A-Series 


| NetApp AFF A20 | https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a20-key-specifications.html#aff-a20-specifications-at-a-glance["AFF A20 Wichtigste Spezifikationen"] 


| NetApp AFF A30 | https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a30-key-specifications.html#aff-a30-specifications-at-a-glance["AFF A30 Wichtigste Spezifikationen"] 
|===


[[netapp-aff-c-series]]
=== NetApp AFF C-Series

Einstiegsmodelle NetApp AFF C-Series Speichercontroller werden für den Einsatz in FlexPod Express unterstützt. Weitere Informationen sind im https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Technische Spezifikationen der AFF C-Series"^] Datenblatt und in der https://hwu.netapp.com/["NetApp Hardware Universe"^] zu finden. Detaillierte Informationen zu einem bestimmten AFF Modell enthält die plattformspezifische Dokumentation in der folgenden Tabelle.

|===
| Komponente | Dokumentation der AFF C-Series Controller-Plattform 


| NetApp AFF C30 | https://docs.netapp.com/us-en/ontap-systems/c30-60/c30-key-specifications.html["AFF C30 Wichtige Spezifikationen"] 
|===


[[netapp-asa-a-series]]
=== NetApp ASA A-Series

Einstiegsmodelle der NetApp ASA A-Series Speichercontroller werden für die Verwendung in FlexPod Express unterstützt. Weitere Informationen sind im https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA A-Series Technische Spezifikationen"^] Datenblatt und in der https://hwu.netapp.com/["NetApp Hardware Universe"^] zu finden. Detaillierte Informationen zu einem bestimmten ASA Modell enthält die plattformspezifische Dokumentation in der folgenden Tabelle.

|===
| Komponente | NetApp ASA A-Series Controller-Plattform Dokumentation 


| NetApp ASA A20 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a20-key-specifications.html["ASA A20 Wichtige Spezifikationen"] 


| NetApp ASA A30 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a30-key-specifications.html["ASA A30 Wichtige Spezifikationen"] 
|===


[[netapp-asa-c-series]]
=== NetApp ASA C-Series

Einstiegsmodelle der NetApp ASA C-Series Speichercontroller werden für die Verwendung in FlexPod Express unterstützt. Weitere Informationen sind im https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA C-Series Technische Spezifikationen"^] Datenblatt und in der https://hwu.netapp.com/["NetApp Hardware Universe"^] zu finden. Detaillierte Informationen zu einem bestimmten ASA Modell sind in der plattformspezifischen Dokumentation in der folgenden Tabelle aufgeführt.

|===
| Komponente | NetApp ASA C-Series Controller-Plattform Dokumentation 


| NetApp ASA C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA C30 Wichtige Spezifikationen"] 
|===


[[netapp-fas-series]]
=== NetApp FAS Serie

Einstiegsmodelle FAS Speichercontroller werden für den Einsatz in einem FlexPod Express unterstützt. Detaillierte Spezifikationen für alle FAS Speichercontroller sind im  https://hwu.netapp.com/["NetApp Hardware Universe"^] verfügbar. Ausführliche Informationen zu einem bestimmten FAS Modell sind in der plattformspezifischen Dokumentation in der folgenden Tabelle zu finden.

|===
| Komponente | Dokumentation der Controller-Plattform der FAS Serie 


| FAS2750-Serie | https://docs.netapp.com/us-en/ontap-systems/fas2700/overview.html["FAS2750 Wichtige Spezifikationen"^] 


| FAS2820-Serie | https://docs.netapp.com/us-en/ontap-systems/fas2800/overview.html["FAS2820 Wichtige Spezifikationen"^] 


| FAS50 Serie | https://docs.netapp.com/us-en/ontap-systems/fas50/overview.html["FAS50 Wichtige Spezifikationen"^] 
|===


[[netapp-disk-shelves]]
=== NetApp Platten-Shelves

Die technischen Spezifikationen für NetApp Festplattengehäuse umfassen den Formfaktor, die Anzahl der Laufwerke pro Gehäuse und die Shelf-I/O-Module; diese Dokumentation befindet sich in der folgenden Tabelle. Weitere Informationen sind im  https://hwu.netapp.com/["NetApp Hardware Universe"^] zu finden.

|===
| Komponente | Dokumentation des NetApp FAS/AFF Festplatten-Shelf 


| NetApp DS212C Festplatten-Shelf | https://www.netapp.com/data-storage/disk-shelves-storage-media/["DS212C Disk Shelf-Dokumentation"] 


| NetApp DS224C Festplatten-Shelf | https://www.netapp.com/data-storage/disk-shelves-storage-media/["DS224C Festplatten-Shelf-Dokumentation"] 


| NetApp DS460C Festplatten-Shelf | https://www.netapp.com/data-storage/disk-shelves-storage-media/["DS460C Festplatten-Shelf-Dokumentation"] 


| NetApp NS224 Disk-Shelf | https://www.netapp.com/data-storage/disk-shelves-storage-media/["NS224 Disk Shelf-Dokumentation"] 


| NS224 mit NSM 100B Festplatteneinschub | https://www.netapp.com/data-storage/disk-shelves-storage-media/["NS224 mit NSM 100B Festplattengehäuse Dokumentation"] 
|===


[[netapp-drives]]
=== NetApp Laufwerke

Die technischen Spezifikationen für NetApp Laufwerke umfassen Formfaktor Größe, Festplattenkapazität, Festplatten-U/min, unterstützende Controller und ONTAP Versionsanforderungen. Diese Spezifikationen finden Sie im Abschnitt Laufwerke des http://hwu.netapp.com/Drives/Index?queryId=1581392["NetApp Hardware Universe"^].
