---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_cisco_components.html 
keywords: cisco, components, server, options, rack, ucs, nexus, switches, x-series-direct, c-series 
summary: Cisco leistet einen erheblichen Beitrag zum Design und der Architektur von FlexPod Express und steuert die Computing- und Networking-Schichten der Lösung. 
---
= Komponenten von Cisco
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Cisco leistet einen erheblichen Beitrag zum Design und der Architektur von FlexPod Express und steuert die Computing- und Networking-Schichten der Lösung. In diesem Abschnitt werden die Cisco Komponenten UCS und Cisco Nexus beschrieben, die für FlexPod Express verfügbar sind.



== Blade Server-Optionen der Cisco UCS B-Serie

Cisco UCS B-Series Blades, die derzeit auf der Cisco UCS Mini-Plattform unterstützt werden, sind B200 M5 und B420 M4. Weitere Blades werden in der folgenden Tabelle aufgeführt, sobald sie auf der Cisco UCS Mini-Plattform unterstützt werden.

|===
| Cisco UCS B-Series Server | Teilenummer | Technische Spezifikationen 


| CISCO UCS B200 M5 | UCSB-B200-M5 | https://www.cisco.com/c/en/us/support/servers-unified-computing/ucs-b200-m5-blade-server/model.html[] 


| CISCO UCS B200 M4 | UCSB-B200-M4 | http://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/b200m4-specsheet.pdf[] 


| CISCO UCS B420 M4 | UCSB-B420-M4 | http://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/b420m4-spec-sheet.pdf[] 
|===


== Rack Server-Optionen für Cisco UCS C-Serie

Cisco UCS C-Series Blades sind als 1-HE- und 2-HE-Varianten mit verschiedenen CPU-, Speicher- und E/A-Optionen erhältlich. Die in der folgenden Tabelle aufgeführten Teilenummern beziehen sich auf den Basis-Server; sie beinhalten keine CPUs, Speicher, Festplatten, PCIe-Karten oder den Cisco FEX. Es stehen zahlreiche Konfigurationsoptionen zur Verfügung und werden in FlexPod unterstützt.

|===
| Rack Server der Cisco UCS C-Serie | Teilenummer | Technische Spezifikationen 


| CISCO UCS C220 M4 | UCSC-C220-M4S | http://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/c220m4-sff-spec-sheet.pdf[] 


| CISCO UCS C240 M4 | UCSC-C240-M4S | http://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/c240m4-sff-spec-sheet.pdf[] 


| CISCO UCS C460 M4 | UCSC-C460-M4 | http://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/c460m4_specsheet.pdf[] 
|===


== Cisco Nexus Switches

Für alle FlexPod Express-Architekturen werden redundante Switches benötigt.

Die FlexPod Express mit NetApp AFF oder FAS-Architektur basiert auf dem Cisco Nexus 31108 Switch. FlexPod Express mit der Cisco UCS Mini (Cisco UCS-managed) Architektur wird mit dem Cisco Nexus 3524 Switch validiert. Diese Konfiguration kann auch mit einem Standard-Switch bereitgestellt werden.

Das FlexPod Express mit E-Series kann mit einem Standard-Switch bereitgestellt werden.

Die folgende Tabelle listet die Teilenummern für das Cisco Nexus Series-Chassis auf; zusätzliche SFP- oder Erweiterungsmodule sind nicht enthalten.

|===
| Cisco Nexus Series Switch | Teilenummer | Technische Spezifikationen 


| Cisco Nexus 3048 | N3K-C3048TP-1GE | http://www.cisco.com/c/en/us/products/collateral/switches/nexus-3000-series-switches/data_sheet_c78-685363.html[] 


| Cisco Nexus 31108 | N3K-C31108PC-V | http://www.cisco.com/c/en/us/products/switches/nexus-31108pc-v-switch/index.html[] 


| Cisco Nexus 9396 | N9K-C9396PX | http://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-729405.html[] 


| Cisco Nexus 3172 | N3K-C3172 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-3000-series-switches/data_sheet_c78-729483.html[] 
|===


== Lizenzoptionen für Cisco Support

Für alle Cisco-Geräte in der FlexPod Express-Architektur sind gültige SMARTnet-Supportverträge erforderlich.


NOTE: Die erforderlichen Lizenzen und die Teilenummern für diese Lizenzen sollten von Ihrem Vertriebsmitarbeiter überprüft werden, da sie je nach Produkt unterschiedlich sein können.

In der folgenden Tabelle sind die Cisco Support-Lizenzoptionen aufgeführt.

|===
| Cisco Support-Lizenzierung | Lizenzhandbuch 


| SMARTnet 24x7x4 | http://www.cisco.com/web/services/portfolio/product-technical-support/smartnet/index.html[] 
|===