---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, flexpod, express, aff, fas, asa 
summary: In diesem Abschnitt werden die Konnektivitätsanforderungen für die verschiedenen Versionen von FlexPod Express beschrieben. 
---
= Konnektivitätsanforderungen erfüllen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In diesem Abschnitt werden die Konnektivitätsanforderungen für die verschiedenen Versionen von FlexPod Express beschrieben.



== Konnektivitätsanforderungen für FlexPod Express mit NetApp AFF/ ASA/ FAS

Die Konnektivitätsanforderungen für FlexPod Express mit NetApp AFF/ ASA/ FAS umfassen:

* NetApp Speichercontroller müssen direkt mit den Cisco Nexus Switches verbunden werden.
* Für UCS X-series Direct-Bereitstellungen können die NetApp Speichercontroller direkt mit den eingebetteten Fabric Interconnects verbunden werden.
* Es können keine zusätzlichen Geräte zwischen den Kern-FlexPod-Komponenten inline platziert werden.
* Virtuelle Portkanäle (vPCs) werden benötigt, um die Cisco Nexus 9000-Serie Switches mit den NetApp Speichercontrollern zu verbinden.
* Dies ist zwar nicht erforderlich, jedoch wird die Unterstützung für Jumbo Frames in der gesamten Umgebung empfohlen.

