---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, aff, asa, fas, cimc, configuration, rack, servers, ucs 
summary: In diesem Abschnitt werden die Mindestanforderungen an die Hardware für die verschiedenen Versionen von FlexPod Express beschrieben. 
---
= Mindestanforderungen an die Hardware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In diesem Abschnitt werden die Mindestanforderungen an die Hardware für die verschiedenen Versionen von FlexPod Express beschrieben.



== FlexPod Express mit NetApp AFF/ ASA/ FAS

Die Hardwareanforderungen für FlexPod Express-Lösungen, die NetApp AFF, ASA oder FAS Controller als zugrunde liegenden Speicher verwenden, umfassen die in diesem Abschnitt beschriebenen Konfigurationen.

Die Mindesthardwareanforderungen für FlexPod Express sind unten aufgeführt:

* Zwei 10Gbps Standard-Ethernet-Switches in redundanter Konfiguration (Cisco Nexus 9200 und 9300 Modelle)
* Cisco UCS C-Series Standalone-Rackserver mit CIMC-basierter Standalone-Rackserverkonfiguration oder Intersight-verwalteter Konfiguration (IMM) oder Cisco UCS X-Series Direct mit Cisco IMM-Konfiguration
* Zwei Einstiegs-Controller der Serien NetApp AFF (A20, A30 oder C30), NetApp ASA (A20, A30 oder C30) oder NetApp FAS (2750 oder 2820) in einer Hochverfügbarkeits-(HA)-Paarkonfiguration, die als Zwei-Node-Cluster bereitgestellt wird

