---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec__netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: NetApp Speichercontroller bilden die Speichergrundlage in der FlexPod Express-Architektur für die Speicherung von System- und Anwendungsdaten. Dieser Abschnitt listet die verschiedenen NetApp Speicheroptionen in der FlexPod Express-Architektur auf. 
---
= Komponenten von NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp Storage-Controller bilden die Storage-Grundlage in der FlexPod Express Architektur für Boot- und Applikationsdaten. In diesem Abschnitt werden die verschiedenen NetApp Optionen in der Architektur von FlexPod Express aufgeführt.



== Optionen für NetApp Storage Controller

Redundante Controller der Serien AFF, ASA oder FAS sind in der FlexPod Express-Architektur erforderlich. Die Controller führen die ONTAP-Software aus. Bei der Bestellung der Speichercontroller kann die bevorzugte Softwareversion auf den Controllern vorinstalliert werden. Für ONTAP kann das Cluster entweder mit einem Paar Cluster-Interconnect-Switches oder in einer Cluster-ohne-Switches-Konfiguration bereitgestellt werden.


NOTE: Eine Cluster ohne Switches-Konfiguration wird nur für eine Zwei-Node-Konfiguration unterstützt. Cluster-Interconnect-Switches sind für Konfigurationen mit mehr als 4 Knoten erforderlich und für eine Zwei-Node-Konfiguration optional.

Je nach gewählter Speicherplattform stehen verschiedene Optionen und Konfigurationen zur Verfügung. Für Details zu diesen zusätzlichen Komponenten wenden Sie sich bitte an Ihren Vertriebsmitarbeiter.

Die in der folgenden Tabelle aufgeführten Controller-Familien eignen sich für den Einsatz in einer FlexPod-Lösung, da ihre Anbindung an die Cisco Nexus Switches nahtlos erfolgt. Siehe die http://hwu.netapp.com/["NetApp Hardware Universe"^]für spezifische Kompatibilitätsdetails zu den einzelnen Controller-Modellen.

|===
| NetApp Einstiegs-Speicherfamilie für FlexPod Express | Modell | Technische Spezifikationen 


.2+| AFF A-Serie | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["AFF A-Series - Dokumentation"] 


| A30 


| AFF C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["AFF C-Series Dokumentation"] 


.2+| ASA A-Series | A20 .2+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA A-Series Dokumentation"] 


| A30 


| ASA C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA C-Series-Dokumentation"] 


.2+| FAS | FAS 2750 .2+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS-Dokumentation"] 


| FAS 2820 
|===


== NetApp Platten-Shelves und Festplatten

Für die Speicherkontroller wird mindestens ein NetApp Festplattengehäuse benötigt.

Der ausgewählte NetApp Shelf-Typ bestimmt, welche Laufwerkstypen in diesem Shelf verfügbar sind.


NOTE: Alle Festplatten-Shelfs und Festplatten-Teilenummern können bei Ihrem Vertriebsmitarbeiter angegeben werden.

Weitere Informationen zu den unterstützten Laufwerken erhalten Sie über den Link NetApp Hardware Universe in der folgenden Tabelle, und wählen Sie dann unterstützte Laufwerke aus.

In der folgenden Tabelle sind die NetApp Platten-Shelf-Optionen sowie die unterstützt Laufwerke für jeden Shelf-Typ, die auf NetApp Hardware Universe zu finden sind, aufgeführt. Folgen Sie dem Link Hardware Universe, wählen Sie die Version der von Ihnen verwendeten ONTAP aus und wählen Sie den Shelf-Typ aus. Klicken Sie unter dem Shelf-Image auf Unterstützte Laufwerke, um die Laufwerke anzuzeigen, die für bestimmte Versionen von ONTAP und die Platten-Shelfs unterstützt werden.

|===
| Festplatten-Shelf | Technische Spezifikationen 


| DS212C .5+| https://hwu.netapp.com/DetailViews/Home.aspx["Festplatten-Shelfs und unterstützte Storage-Medien auf NetApp Hardware Universe"] 


| DS224C 


| DS460C 


| NS224 


| NS224 mit NSM100B 
|===


== NetApp Software-Lizenzoptionen

Die folgende Tabelle listet die NetApp Softwarelizenzierungsoptionen auf.

|===
| NetApp Softwarelizenzierung | Technische Spezifikationen 


| ONTAP One oder ONTAP base für AFF und FAS .2+| Wenden Sie sich an Ihr NetApp Vertriebsteam, um weitere Lizenzierungsinformationen zu erhalten. 


| ONTAP One für SAN für ASA 
|===


== NetApp Support – Lizenzoptionen

Die SupportEdge Premium Lizenzen sind erforderlich. Die Teilenummern dieser Lizenzen variieren je nach den im FlexPod Express Design ausgewählten Optionen.

Die folgende Tabelle listet die NetApp Support-Lizenzierungsoptionen für NetApp AFF, ASA und FAS Storage-Systeme auf.

|===
| Lizenzierung des NetApp Supports | Teilenummer | Technische Spezifikationen 


| SupportEdge Premium4 Stunden vor Ort; Monate: 36 | CS-O2-4HR | link:https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf["https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf"] 
|===