---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, flexpod, express, aff, fas, asa 
summary: In diesem Abschnitt werden die Konnektivitätsanforderungen für die verschiedenen Versionen von FlexPod Express beschrieben. 
---
= Konnektivitätsanforderungen erfüllen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In diesem Abschnitt werden die allgemeinen Konnektivitätsanforderungen für die verschiedenen Versionen von FlexPod Express erläutert.



== Konnektivitätsanforderungen für FlexPod Express mit NetApp AFF/ ASA/ FAS

Die Verbindungsanforderungen für FlexPod Express mit NetApp AFF/ ASA/ FAS umfassen im Allgemeinen:

* NetApp Speichercontroller müssen direkt mit den Cisco Nexus Switches verbunden werden.
* Für Cisco UCS X-Series Direct-Bereitstellungen können die NetApp Speichercontroller direkt mit den eingebetteten Fabric Interconnects verbunden werden.
* Es können keine zusätzlichen Geräte zwischen den Kern-FlexPod-Komponenten inline platziert werden.
* Virtuelle Portkanäle (vPCs) werden benötigt, um die Cisco Nexus 9000-Serie Switches mit den NetApp Speichercontrollern zu verbinden.
* Dies ist zwar nicht erforderlich, jedoch wird die Unterstützung für Jumbo Frames in der gesamten Umgebung empfohlen.


Im link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_express_topologies.html["FlexPod Express-Topologien"^]Abschnitt finden sich die spezifischen Konnektivitätsanforderungen für jede Topologie.
