---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_supported_versus_validated_flexpod_configurations.html 
keywords: supported, versus, validated, flexpod, express, configurations, imt 
summary: 'Die FlexPod-Architektur wird durch den in diesem Dokument beschriebenen Regelsatz definiert. Die Hardware-Komponenten und Software-Konfigurationen müssen von der Cisco Hardware Compatibility List (HCL) und dem NetApp IMT unterstützt werden.' 
---
= Unterstützte und validierte FlexPod Konfigurationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Die FlexPod Architektur wird durch die in diesem Dokument beschriebenen Regeln definiert. Die Hardwarekomponenten und Softwarekonfigurationen müssen von der  https://ucshcltool.cloudapps.cisco.com/public/hcl["Cisco Hardware Compatibility List (HCL)"^] und der  http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool (IMT)"^] unterstützt werden.

Jedes Cisco Validated Design (CVD) oder NetApp Verified Architecture (NVA) stellt eine validierte FlexPod Konfiguration dar. Cisco und NetApp dokumentieren diese Konfigurationskombinationen und validieren sie durch umfassende End-to-End-Tests. Die FlexPod Implementierungen, die von diesen Konfigurationen abweichen, werden vollständig unterstützt, sofern sie den Richtlinien in diesem Dokument entsprechen und alle Komponenten in der Cisco HCL und NetApp IMT als kompatibel aufgeführt sind.

Beispielsweise werden zusätzliche Storage-Controller oder Cisco UCS Server hinzugefügt und Software-Upgrades auf neuere Versionen durchgeführt, wenn die Software, Hardware und Konfigurationen den in diesem Dokument definierten Richtlinien entsprechen.
