---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_overview.html 
keywords: flexpod, express, technical, specifications, architecture, cisco, ucs 
summary: 'FlexPod Express ist eine vordefinierte, nach Best Practices entwickelte Architektur, die auf dem Cisco Unified Computing System (Cisco UCS) und der Cisco Nexus Familie von Switches aufbaut, und die Speicherschicht wird mithilfe des NetApp FAS oder des NetApp E-Series Storage realisiert.' 
---
= TR-4293: FlexPod Express-Technische Spezifikationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Karthick Radhakrishnan, Arvind Ramakrishnan, Lindsey Street, Savita Kumari, NetApp

[role="lead"]
FlexPod Express ist eine vorkonfigurierte, bewährte Architektur, die auf dem Cisco Unified Computing System (Cisco UCS) und der Cisco Nexus-Familie von Switches basiert, und die Speicherschicht wird mit NetApp FAS oder NetApp E-Series Storage realisiert. FlexPod Express eignet sich als Plattform für den Betrieb verschiedener Virtualisierungshypervisoren und Bare-Metal-Betriebssysteme (OSs) sowie Enterprise-Workloads.

FlexPod Express bietet nicht nur eine Basiskonfiguration, sondern auch die Flexibilität, an unterschiedliche Anwendungsfälle und Anforderungen angepasst und optimiert zu werden. Dieses Dokument kategorisiert die FlexPod Express-Konfigurationen anhand des verwendeten Speichersystems, FlexPod Express mit NetApp FAS und FlexPod Express mit E-Series.
