---
sidebar: sidebar 
permalink: hybrid-cloud/cloud-fabricpool_introduction.html 
keywords: flexpod, fabricpool, inactive, data, tiering, amazon, aws, s3 
summary: In diesem technischen Bericht wird die FabricPool Daten-Tiering-Funktion von NetApp ONTAP im Rahmen einer konvergenten FlexPod Infrastrukturarchitektur von NetApp und Cisco besprochen. 
---
= TR-4801: FlexPod mit FabricPool – Inactive Data Tiering in Amazon AWS S3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Scott Kovacs, NetApp

[role="lead"]
Flash-Storage-Preise fallen weiter und sind somit für Workloads und Applikationen verfügbar, die zuvor nicht in Betracht gezogen wurden. Eine möglichst effiziente Nutzung der Storage-Investitionen ist für IT-Manager jedoch nach wie vor von zentraler Bedeutung. IT-Abteilungen sehen sich immer noch gezwungen, leistungsstärkere Services mit nur geringen oder gar keinen Budgetzuteilungen bereitzustellen. Zur Erfüllung dieser Anforderungen können Sie mit NetApp FabricPool die Wirtschaftlichkeit der Cloud nutzen, indem Sie selten genutzte Daten aus teurem Flash-Storage vor Ort auf einen kostengünstigeren Storage-Tier in der Public Cloud verschieben. Das Verschieben selten genutzter Daten in die Cloud setzt wertvollen Flash-Storage auf AFF- oder FAS-Systemen frei, sodass geschäftskritische Workloads mehr Kapazität auf das hochperformante Flash-Tier bereitstellen können.

In diesem technischen Bericht wird die FabricPool Daten-Tiering-Funktion von NetApp ONTAP im Rahmen einer konvergenten FlexPod Infrastrukturarchitektur von NetApp und Cisco besprochen. Sie sollten mit der konvergenten Infrastrukturarchitektur für FlexPod Datacenter und der ONTAP Storage-Software vertraut sein, um die in diesem technischen Bericht vorgestellten Konzepte voll nutzen zu können. Da wir mit FlexPod und ONTAP vertraut sind, sprechen wir über FabricPool, seine Funktionsweise und seine Möglichkeiten zur effizienteren Nutzung von Flash-Storage vor Ort. Ein Großteil des Inhalts dieses Berichts wird unter ausführlicher behandelt https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598 FabricPool Best Practices"^] Und anderer ONTAP Produktdokumentation zu bieten. Der Inhalt wurde für eine FlexPod Infrastruktur komprimiert und deckt nicht alle Anwendungsfälle für FabricPool ab. Alle analysierte Merkmale und Konzepte sind in ONTAP 9.6 erhältlich.

Weitere Informationen zu FlexPod finden Sie in https://www.netapp.com/pdf.html?item=/media/12424-tr4036.pdf["TR-4036 FlexPod Datacenter – Technische Spezifikationen"^].
