---
sidebar: sidebar 
permalink: hybrid-cloud/fhc-cvoe-installation-and-configuration.html 
keywords: cloud volumes ontap, flexpod, ontap netapp console, installation, configuration 
summary: In diesem Abschnitt wird die Installation und Konfiguration von Cloud Volumes ONTAP, FlexPod, ONTAP -Speicher und der NetApp Console beschrieben. 
---
= Installation und Konfiguration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:fhc-cvoe-solution-components.html["Früher: Lösungskomponenten."]



== NetApp Cloud Volumes ONTAP Implementierung

Führen Sie die folgenden Schritte aus, um Ihre Cloud Volumes ONTAP-Instanz zu konfigurieren:

. Vorbereitung der Public-Cloud-Service-Provider-Umgebung
+
Für die Lösungskonfiguration müssen Sie die Umgebungsdetails Ihres Public Cloud-Service-Providers erfassen. Zur Vorbereitung der Amazon Web Services (AWS)-Umgebung benötigen Sie beispielsweise den AWS-Zugriffsschlüssel, den AWS-Geheimschlüssel und weitere Netzwerkdetails wie Region, VPC, Subnetz usw.

. Konfigurieren Sie das VPC-Endpunkt-Gateway.
+
Um die Verbindung zwischen der VPC und dem AWS S3-Service zu ermöglichen, ist ein VPC-Endpunkt-Gateway erforderlich. Damit wird die Sicherung auf CVO, einem Endpunkt mit dem Gateway-Typ, aktiviert.

. Greifen Sie auf die NetApp Console zu.
+
Um auf die Konsole und andere Cloud-Dienste zuzugreifen, müssen Sie sich anmelden bei https://cloudmanager.netapp.com/["NetApp Console"^] Die  Informationen zum Einrichten von Arbeitsbereichen und Benutzern im Konsolenkonto finden Sie unter https://docs.netapp.com/us-en/console-setup-admin/index.html["Einrichtung und Verwaltung der NetApp Console"^] Die  Sie benötigen ein Konto, das die Berechtigung besitzt, den Console-Agenten direkt von der Console aus bei Ihrem Cloud-Anbieter bereitzustellen.  Um die benötigten Berechtigungen zu erhalten, lesen Sie bitte Folgendes: https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions.html["Berechtigungsübersicht für die NetApp Console"^] Die

. Konsolenagent bereitstellen.
+
Bevor Sie ein Cloud Volume ONTAP -System hinzufügen, müssen Sie einen Konsolenagenten bereitstellen.  Die Konsole fordert Sie auf, wenn Sie versuchen, Ihr erstes Cloud Volumes ONTAP System ohne installierten Konsolenagenten zu erstellen.  Informationen zur Bereitstellung eines Console-Agenten in AWS über die Console finden Sie unter https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html["Installationsoptionen für Konsolenagenten in AWS"^] Die

. Starten Sie Cloud Volumes ONTAP in AWS.
+
Sie können Cloud Volumes ONTAP in einer Einzelsystemkonfiguration oder als HA-Paar in AWS starten. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-aws.html["Lesen Sie die Schritt-für-Schritt-Anleitung"^].

+
Ausführliche Informationen zu diesen Schritten finden Sie im https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["Schnellstartanleitung für Cloud Volumes ONTAP in AWS"^].

+
Bei dieser Lösung haben wir ein Cloud Volumes ONTAP System mit einem einzigen Knoten in AWS bereitgestellt.





== Lokale FlexPod-Implementierung

Informationen über die Designdetails von FlexPod with UCS X-Series, VMware and NetApp ONTAP finden Sie im https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html["FlexPod Datacenter mit Cisco UCS X-Serie"^] Designleitfaden Dieses Dokument enthält Anleitungen zum Design, wie Sie die von Cisco Intersight gemanagte Plattform der UCS X-Serie in die FlexPod Datacenter-Infrastruktur integrieren können.

Informationen zur Bereitstellung der lokalen FlexPod-Instanz finden Sie unter https://netapp-https:/www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmware_7u2.htmlmy.sharepoint.com/personal/dorianh_netapp_com/Documents/Projects/Github%20Conversions/FlexPod/TR-4960/TR-4960%20FlexPod%20hybrid%20cloud%20with%20CVO%20for%20Epic%20latest-Feb14.docx["Implementierungsleitfaden"^].

Dieses Dokument enthält Anleitungen zur Implementierung, wie Sie die von Cisco Intersight gemanagte Plattform der UCS X-Serie in eine FlexPod Datacenter-Infrastruktur integrieren können. Das Dokument behandelt sowohl Konfigurationen als auch Best Practices für eine erfolgreiche Implementierung.

FlexPod kann sowohl im UCS Managed Mode als auch im Cisco Intersight Managed Mode (IMM) implementiert werden. Wenn Sie FlexPod im verwalteten UCS-Modus bereitstellen, finden Sie dies https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html["Designleitfaden"^] Und das https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html["Implementierungsleitfaden"^].

Die FlexPod-Implementierung kann mit „Infrastructure-as-Code“ über Ansible automatisiert werden. Nachfolgend finden Sie die Links zu GitHub Repositorys für eine End-to-End FlexPod Implementierung:

* Ansible-Konfiguration von FlexPod mit Cisco UCS im UCS Managed Mode, NetApp ONTAP und VMware vSphere sind sichtbar https://github.com/ucs-compute-solutions/FlexPod-UCSM-M6["Hier"^].
* Ansible-Konfiguration von FlexPod mit Cisco UCS in IMM, NetApp ONTAP und VMware vSphere sind sichtbar https://github.com/ucs-compute-solutions/FlexPod-IMM-4.2.2["Hier"^].




== On-Premises-ONTAP Storage-Konfiguration

In diesem Abschnitt werden einige der wichtigen für diese Lösung spezifischen ONTAP Konfigurationsschritte beschrieben.

. Konfigurieren Sie eine SVM, auf der der iSCSI-Dienst ausgeführt wird.
+
....
1. vserver create -vserver Healthcare_SVM -rootvolume Healthcare_SVM_root -aggregate aggr1_A400_G0312_01 -rootvolume-security-style unix
2. vserver add-protocols -vserver Healthcare_SVM -protocols iscsi
3. vserver iscsi create -vserver Healthcare_SVM

   To verify:

   A400-G0312::> vserver iscsi show -vserver Healthcare_SVM
   Vserver: Healthcare_SVM
   Target Name:
   iqn.1992-08.com.netapp:sn.1fbf00f438c111ed866cd039ea91fb56:vs.3
   Target Alias: Healthcare_SVM
   Administrative Status: up
....
+
Wenn die iSCSI-Lizenz während der Clusterkonfiguration nicht installiert wurde, müssen Sie die Lizenz installieren, bevor Sie den iSCSI-Dienst erstellen.

. Erstellen Sie ein FlexVol-Volume.
+
....
1. volume create -vserver Healthcare_SVM -volume hc_iscsi_vol -aggregate aggr1_A400_G0312_01 -size 500GB -state online -policy default -space guarantee none
....
. Fügen Sie Schnittstellen für iSCSI-Zugriff hinzu.
+
....
1. network interface create -vserver Healthcare_SVM -lif iscsi-lif-01a -service-policy default-data-iscsi -home-node <st-node01> -home-port a0a-<infra-iscsi-a-vlan-id> -address <st-node01-infra-iscsi-a-ip> -netmask <infra-iscsi-a-mask> -status-admin up
2. network interface create -vserver Healthcare_SVM -lif iscsi-lif-01b -service-policy default-data-iscsi -home-node <st-node01> -home-port a0a-<infra-iscsi-b-vlan-id> -address <st-node01-infra-iscsi-b-ip> -netmask <infra-iscsi-b-mask> -status-admin up
3. network interface create -vserver Healthcare_SVM -lif iscsi-lif-02a -service-policy default-data-iscsi -home-node <st-node02> -home-port a0a-<infra-iscsi-a-vlan-id> -address <st-node02-infra-iscsi-a-ip> -netmask <infra-iscsi-a-mask> -status-admin up
4. network interface create -vserver Healthcare_SVM -lif iscsi-lif-02b -service-policy default-data-iscsi -home-node <st-node02> -home-port a0a-<infra-iscsi-b-vlan-id> -address <st-node02-infra-iscsi-b-ip> -netmask <infra-iscsi-b-mask> -status-admin up
....
+
In dieser Lösung haben wir vier iSCSI Logical Interfaces (LIFs) erstellt, zwei auf jedem Node.

+
Nachdem die FlexPod Instanz mit bereitgestelltem vCenter ausgeführt wurde und alle ESXi Hosts hinzugefügt wurden, müssen wir eine Linux VM implementieren, die als Server fungiert, der mit dem NetApp ONTAP Storage verbunden ist und auf diesen zugreift. In dieser Lösung haben wir eine CentOS 8-Instanz in vCenter installiert.

. Erstellen Sie eine LUN.
+
....
1. lun create -vserver Healthcare_SVM -path /vol/hc_iscsi_vol/iscsi_lun1 -size 200GB -ostype linux -space-reserve disabled
....
+
Für eine ODB (EHR Operational Database), ein Journal und Applikations-Workloads empfiehlt EHR die Bereitstellung von Storage für Server als iSCSI-LUNs. NetApp unterstützt auch die Verwendung von FCP und NVMe/FC, wenn Sie Versionen von AIX und den RHEL Betriebssystemen verwenden können, wodurch die Performance verbessert wird. FCP und NVMe/FC können gleichzeitig im selben Fabric vorhanden sein.

. Erstellen einer Initiatorgruppe
+
....
1. igroup create -vserver Healthcare_SVM -igroup ehr -protocol iscsi -ostype linux -initiator iqn.1994-05.com.redhat:8e91e9769336
....
+
IGroups ermöglichen den Serverzugriff auf LUNs. Für Linux-Host kann der Server-IQN in der Datei gefunden werden `/etc/iscsi/initiatorname.iscsi`.

. Ordnen Sie die LUN der Initiatorgruppe zu.
+
....
1. lun mapping create -vserver Healthcare_SVM -path /vol/hc_iscsi_vol/iscsi_lun1 -igroup ehr -lun-id 0
....




== Fügen Sie der NetApp Console lokalen FlexPod Speicher hinzu.

Führen Sie die folgenden Schritte aus, um Ihren FlexPod -Speicher mithilfe der Konsole zum System hinzuzufügen.

. Wählen Sie im Navigationsmenü *Speicher* > *Systeme*.
. Klicken Sie auf der Seite „Systeme“ auf *System hinzufügen* und wählen Sie *Lokale Installation* aus.
. Wählen Sie *On-Premise ONTAP*. Klicken Sie Auf *Weiter*.
. Geben Sie auf der Seite ONTAP Cluster Details die Cluster-Management-IP-Adresse und das Kennwort für das Admin-Benutzerkonto ein. Klicken Sie dann auf *Hinzufügen*.
. Geben Sie auf der Seite Details und Anmeldeinformationen einen Namen und eine Beschreibung für die Arbeitsumgebung ein, und klicken Sie dann auf *Go*.
+
Die Konsole erkennt den ONTAP Cluster und fügt ihn als System auf der Seite „Systeme“ hinzu.



Ausführliche Informationen finden Sie auf der Seite https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html["Erkennen von ONTAP Clustern vor Ort"^].

link:fhc-cvoe-san-configuration.html["Weiter: SAN-Konfiguration."]
