---
sidebar: sidebar 
permalink: hybrid-cloud/fhc-cvoe-san-configuration.html 
keywords: san, configuration, host utility kit, discover storage, multipathing, physical volume, group, logical volume, file system, snapmirror 
summary: In diesem Abschnitt wird die Host-seitige Konfiguration beschrieben, die von EHR zur optimalen Integration der Software in NetApp Storage erforderlich ist. In diesem Segment befassen wir uns insbesondere mit der Host-Integration für Linux-Betriebssysteme. 
---
= SAN-Konfiguration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:fhc-cvoe-installation-and-configuration.html["Zurück: Installation und Konfiguration."]

[role="lead"]
In diesem Abschnitt wird die Host-seitige Konfiguration beschrieben, die von EHR zur optimalen Integration der Software in NetApp Storage erforderlich ist. In diesem Segment befassen wir uns insbesondere mit der Host-Integration für Linux-Betriebssysteme. Verwenden Sie die https://imt.netapp.com/matrix/["NetApp Interoperabilitäts-Matrix-Tool (IMT)"^] Zur Validierung aller Versionen von Software und Firmware.


NOTE: Die folgenden Konfigurationsschritte sind spezifisch für den CentOS 8-Host, der in dieser Lösung verwendet wurde.



== NetApp Host Utility Kit

NetApp empfiehlt die Installation des NetApp Host Utility Kit (Host Utilities) auf den Betriebssystemen der Hosts, die mit den NetApp Storage-Systemen verbunden sind und auf diese zugreifen. Native Microsoft Multipath-I/O (MPIO) wird unterstützt. Das Betriebssystem muss für Multipathing asymmetrisch (Asymmetric Logical Unit Access, ALUA) fähig sein. Durch das Installieren der Host Utilities werden die HBA-Einstellungen (Host Bus Adapter) für den NetApp Storage konfiguriert.

NetApp Host Utilities können heruntergeladen werden https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["Hier"^]. In dieser Lösung haben wir Linux Host Utilities 7.1 auf dem Host installiert.

....
[root@hc-cloud-secure-1 ~]# rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64.rpm
....


== ONTAP Storage entdecken

Stellen Sie sicher, dass der iSCSI-Dienst ausgeführt wird, wenn die Anmeldungen erfolgen sollen. Um den Anmelde-Modus für ein bestimmtes Portal auf einem Ziel oder für alle Portale auf einem Ziel festzulegen, verwenden Sie die `iscsiadm` Befehl.

....
[root@hc-cloud-secure-1 ~]# rescan-scsi-bus.sh
[root@hc-cloud-secure-1 ~]# iscsiadm -m discovery -t sendtargets -p <iscsi-lif-ip>
[root@hc-cloud-secure-1 ~]# iscsiadm -m node -L all
....
Jetzt können Sie verwenden `sanlun` Um Informationen über die mit dem Host verbundenen LUNs anzuzeigen. Stellen Sie sicher, dass Sie als root auf dem Host angemeldet sind.

....
[root@hc-cloud-secure-1 ~]# sanlun lun show
controller(7mode/E-Series)/
                                    device    host             lun
vserver(cDOT/FlashRay) lun-pathname filename  adapter protocol size   product
-----------------------------------------------------------------------------
Healthcare_SVM                       /dev/sdb host33  iSCSI    200g    cDOT
                       /vol/hc_iscsi_vol/iscsi_lun1

Healthcare_SVM                       /dev/sdc host34  iSCSI    200g    cDOT
                       /vol/hc_iscsi_vol/iscsi_lun1
....


== Konfigurieren Sie Multipathing

Device Mapper Multipathing (DM-Multipath) ist ein natives Multipathing-Dienstprogramm in Linux. Es kann für Redundanz und zur Verbesserung der Leistung verwendet werden. Die Software aggregiert oder kombiniert die zahlreichen I/O-Pfade zwischen Servern und Storage und erstellt somit ein einziges Gerät auf Betriebssystemebene.

. Bevor Sie DM-Multipath auf Ihrem System einrichten, stellen Sie sicher, dass Ihr System aktualisiert wurde und den enthält `device-mapper-multipath` Paket.
+
....
[root@hc-cloud-secure-1 ~]# rpm -qa|grep multipath
device-mapper-multipath-libs-0.8.4-31.el8.x86_64
device-mapper-multipath-0.8.4-31.el8.x86_64
....
. Die Konfigurationsdatei ist die `/etc/multipath.conf` Datei: Aktualisieren Sie die Konfigurationsdatei wie unten gezeigt.
+
....
[root@hc-cloud-secure-1 ~]# cat /etc/multipath.conf
defaults {
   path_checker      readsector0
   no_path_retry      fail
}
devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
....
. Aktivieren und starten Sie die Multipath-Services.
+
....
[root@hc-cloud-secure-1 ~]# systemctl enable multipathd.service
[root@hc-cloud-secure-1 ~]# systemctl start  multipathd.service
....
. Fügen Sie das ladbare Kernelmodul hinzu `dm-multipath` Und starten Sie den Multipath-Dienst neu. Überprüfen Sie abschließend den Multipathing-Status.
+
....
[root@hc-cloud-secure-1 ~]# modprobe -v dm-multipath
insmod /lib/modules/4.18.0-408.el8.x86_64/kernel/drivers/md/dm-multipath.ko.xz

[root@hc-cloud-secure-1 ~]# systemctl restart multipathd.service

[root@hc-cloud-secure-1 ~]# multipath -ll
3600a09803831494c372b545a4d786278 dm-2 NETAPP,LUN C-Mode
size=200G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| `- 33:0:0:0 sdb 8:16 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
`- 34:0:0:0 sdc 8:32 active ready running
....



NOTE: Ausführliche Informationen zu diesen Schritten finden Sie unter https://docs.netapp.com/us-en/ontap-sanhost/hu_centos_80.html["Hier"^].



== Erstellen eines physischen Volumes

Verwenden Sie die `pvcreate` Befehl zum Initialisieren eines Blockgeräts, das als physisches Volume verwendet werden soll. Die Initialisierung ist analog zur Formatierung eines Dateisystems.

....
[root@hc-cloud-secure-1 ~]# pvcreate /dev/sdb
Physical volume "/dev/sdb" successfully created.
....


== Volume-Gruppe erstellen

Um eine Volume-Gruppe aus einem oder mehreren physischen Volumes zu erstellen, verwenden Sie die `vgcreate` Befehl. Mit diesem Befehl wird eine neue Volume-Gruppe nach Namen erstellt und ihr mindestens ein physisches Volume hinzugefügt.

....
[root@hc-cloud-secure-1 ~]# vgcreate datavg /dev/sdb
Volume group "datavg" successfully created.
....
Der `vgdisplay` Mit dem Befehl können die Eigenschaften der Volume-Gruppe (z. B. Größe, Extents, Anzahl physischer Volumes usw.) in einem festen Format angezeigt werden.

....
[root@hc-cloud-secure-1 ~]# vgdisplay datavg
  --- Volume group ---
  VG Name               datavg
  System ID
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  1
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                0
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               <200.00 GiB
  PE Size               4.00 MiB
  Total PE              51199
  Alloc PE / Size       0 / 0
  Free  PE / Size       51199 / <200.00 GiB
  VG UUID               C7jmI0-J0SS-Cq91-t6b4-A9xw-nTfi-RXcy28
....


== Erstellung eines logischen Volumes

Wenn Sie ein logisches Volume erstellen, wird das logische Volume mithilfe der freien Extents auf den physischen Volumes, aus denen die Volume-Gruppe besteht, aus einer Volume-Gruppe erstellt.

....
[root@hc-cloud-secure-1 ~]# lvcreate - l 100%FREE -n datalv datavg
Logical volume "datalv" created.
....
Mit diesem Befehl wird ein logisches Volume mit dem Namen erstellt `datalv` Dies belegt den gesamten nicht zugewiesenen Speicherplatz in der Volume-Gruppe `datavg`.



== Erstellen Sie ein Dateisystem

....
[root@hc-cloud-secure-1 ~]# mkfs.xfs -K /dev/datavg/datalv
meta-data=/dev/datavg/datalv     isize=512    agcount=4, agsize=13106944 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=1    bigtime=0 inobtcount=0
data     =                       bsize=4096   blocks=52427776, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=25599, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
....


== Ordner zum Mounten erstellen

....
[root@hc-cloud-secure-1 ~]# mkdir /file1
....


== Mounten Sie das Dateisystem

....
[root@hc-cloud-secure-1 ~]# mount -t xfs /dev/datavg/datalv /file1

[root@hc-cloud-secure-1 ~]# df -k
Filesystem                1K-blocks    Used Available Use% Mounted on
devtmpfs                    8072804       0   8072804   0% /dev
tmpfs                       8103272       0   8103272   0% /dev/shm
tmpfs                       8103272    9404   8093868   1% /run
tmpfs                       8103272       0   8103272   0% /sys/fs/cgroup
/dev/mapper/cs-root        45496624 5642104  39854520  13% /
/dev/sda2                   1038336  258712    779624  25% /boot
/dev/sda1                    613184    7416    605768   2% /boot/efi
tmpfs                       1620652      12   1620640   1% /run/user/42
tmpfs                       1620652       0   1620652   0% /run/user/0
/dev/mapper/datavg-datalv 209608708 1494520 208114188   1% /file1
....
Ausführliche Informationen zu diesen Aufgaben finden Sie auf der Seite link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/logical_volume_manager_administration/lvm_cli["LVM-Administration mit CLI-Befehlen"].



== Datengenerierung

 `Dgen.pl`ist ein Perl-Skript-Datengenerator für den I/O-Simulator von EHR (GenerateIO).  Die Daten innerhalb der LUNs werden mit dem EHR generiert. `Dgen.pl` Skript.  Das Skript ist so konzipiert, dass es Daten erzeugt, die den Daten in einer EHR-Datenbank ähneln.

....
[root@hc-cloud-secure-1 ~]# cd GenerateIO-1.17.3/

[root@hc-cloud-secure-1 GenerateIO-1.17.3]# ./dgen.pl --directory /file1 --jobs 80

[root@hc-cloud-secure-1 ~]# cd /file1/
[root@hc-cloud-secure-1 file1]# ls
dir01  dir05  dir09  dir13  dir17  dir21  dir25  dir29  dir33  dir37  dir41  dir45  dir49  dir53  dir57  dir61  dir65  dir69  dir73  dir77  dir02  dir06  dir10  dir14  dir18  dir22  dir26  dir30  dir34  dir38  dir42  dir46  dir50  dir54  dir58  dir62  dir66  dir70  dir74  dir78  dir03  dir07  dir11  dir15  dir19  dir23  dir27  dir31  dir35  dir39  dir43  dir47  dir51  dir55  dir59  dir63  dir67  dir71  dir75  dir79  dir04  dir08  dir12  dir16  dir20  dir24  dir28  dir32  dir36  dir40  dir44  dir48  dir52  dir56  dir60  dir64  dir68  dir72  dir76  dir80

[root@hc-cloud-secure-1 file1]# df -k .
Filesystem                 1K-blocks  Used       Available  Use%  Mounted on
/dev/mapper/datavg-datalv  209608708  178167156  31441552   85%   /file1
....
Während der Ausführung wird die angezeigt `Dgen.pl` Skript verwendet standardmäßig 85 % des Dateisystems für die Datengenerierung.



== Konfiguration der SnapMirror Replizierung zwischen lokalem ONTAP und Cloud Volumes ONTAP

NetApp SnapMirror repliziert Daten mit hohen Geschwindigkeiten über LAN oder WAN, so dass Sie in virtuellen und herkömmlichen Umgebungen hohe Datenverfügbarkeit und schnelle Datenreplizierung erhalten. Durch das Replizieren und ständige Aktualisieren der sekundären Daten auf NetApp Storage-Systemen sind die Daten immer aktuell und verfügbar. Es sind keine externen Replizierungsserver erforderlich.

Führen Sie die folgenden Schritte aus, um die SnapMirror Replizierung zwischen Ihrem lokalen ONTAP System und CVO zu konfigurieren.

. Wählen Sie im Navigationsmenü *Speicher* > *Systeme*.
. Wählen Sie unter „Systeme“ das System aus, das das Quellvolume enthält, ziehen Sie es auf das System, auf das Sie das Volume replizieren möchten, und wählen Sie dann *Replikation* aus.
+
In den verbleibenden Schritten wird erläutert, wie eine synchrone Beziehung zwischen Cloud Volumes ONTAP und On-Premises-ONTAP-Clustern erstellt werden kann.

. *Einrichtung von Quell- und Ziel-Peering.* Wenn diese Seite angezeigt wird, wählen Sie alle Cluster-LIFs für die Cluster-Peer-Beziehung aus.
. *Auswahl des Quell-Volumes.* Wählen Sie das Volume aus, das Sie replizieren möchten.
. *Zieldatentyp und Tiering.* Wenn es sich bei dem Ziel um ein Cloud Volumes ONTAP-System handelt, wählen Sie den Zieldatentyp aus und wählen, ob Sie Daten-Tiering aktivieren möchten.
. *Zieldatenträger Name:* Geben Sie den Namen des Zieldatenträger an und wählen Sie das Zielaggregat. Wenn das Ziel ein ONTAP-Cluster ist, müssen Sie auch die Ziel-Storage-VM angeben.
. *Maximale Übertragungsrate.* Geben Sie die maximale Übertragungsrate (in Megabyte pro Sekunde) an.
. *Replikationsrichtlinie.* Wählen Sie eine Standardrichtlinie oder klicken Sie auf *zusätzliche Richtlinien* und wählen Sie dann eine der erweiterten Richtlinien aus. Hilfe erhalten Sie unter: https://docs.netapp.com/us-en/cloud-manager-replication/concept-replication-policies.html["Weitere Informationen zu Replizierungsrichtlinien"^].
. *Zeitplan.* Wählen Sie eine einmalige Kopie oder einen wiederkehrenden Zeitplan. Es stehen mehrere Standardzeitpläne zur Verfügung. Wenn Sie einen anderen Zeitplan benötigen, müssen Sie einen neuen Zeitplan auf der erstellen `destination cluster` Verwenden von System Manager.
. *Review.* Überprüfen Sie Ihre Auswahl und klicken Sie auf *Go*.


Ausführliche Informationen zu diesen Konfigurationsschritten finden Sie unter https://docs.netapp.com/us-en/cloud-manager-replication/task-replicating-data.html["Hier"^].

Die Konsole startet den Datenreplikationsprozess.  In diesem Stadium können Sie den *Replikationsdienst* sehen, der zwischen Ihrem lokalen ONTAP System und Cloud Volumes ONTAP eingerichtet wurde.

Im Cloud Volumes ONTAP Cluster können Sie das neu erstellte Volume sehen.

Sie können auch überprüfen, ob die SnapMirror Beziehung zwischen dem lokalen Volume und dem Cloud Volume aufgebaut ist.

Weitere Informationen zur Replikationsaufgabe finden Sie auf der Registerkarte *Replikation*.

link:fhc-cvoe-solution-validation.html["Weiter: Lösungsvalidierung."]
