---
sidebar: sidebar 
permalink: vdi/fpd-citrix-xend-vmw.html 
keywords: cisco, flexpod, all, flash, aff, citrix, vmware, vsphere, stroage, esxi, hypervisor 
summary: 'Dieses Dokument stellt eine Referenzarchitektur für ein Virtual Desktop- und Applikationsdesign bereit. Dazu wird Citrix XenApp/XenDesktop 7.15 auf Basis von Cisco UCS mit NetApp All Flash FAS (AFF) A300 Storage und der Hypervisor-Plattform VMware vSphere ESXi 6.5 verwendet.' 
---
= FlexPod Datacenter mit Citrix XenDesktop/XenApp 7.15 und VMware vSphere 6.5 Update 1 für 6000 Seats
:allow-uri-read: 


Vadim Lebedev, Cisco Chris Rodriguez, NetApp

Dieses Dokument stellt eine Referenzarchitektur für ein Virtual Desktop- und Applikationsdesign bereit. Dazu wird Citrix XenApp/XenDesktop 7.15 auf Basis von Cisco UCS mit NetApp All Flash FAS (AFF) A300 Storage und der Hypervisor-Plattform VMware vSphere ESXi 6.5 verwendet.

Die Virtualisierung von Desktops und Applikationen unterliegt einem ständigen Wandel. Die neuen M5 hochperformanten Cisco UCS Blade Server und Cisco UCS Unified Fabric in Kombination als Teil der FlexPod Proven Infrastructure mit NetApp AFF Storage der neuesten Generation ergeben eine kompaktere, leistungsstärkere, zuverlässigere und effizientere Plattform.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/cisco_ucs_xd715esxi65u1_flexpod.html["FlexPod Datacenter mit Citrix XenDesktop/XenApp 7.15 und VMware vSphere 6.5 Update 1 für 6000 Seats"^]
