---
sidebar: sidebar 
permalink: vdi/fpd-citrix-vir.html 
keywords: flexpod, cisco, data, center, citrix, virtual, apps, vmware, vsphere 
summary: Dieses Dokument enthält die Architektur und das Design einer Virtual Desktop Infrastructure für bis zu 6000 Endbenutzer-Computing. 
---
= FlexPod-Datacenter mit Citrix Virtual Apps & Desktops 1912 LTSR und VMware vSphere 7 für bis zu 6000 Arbeitsplätze
:allow-uri-read: 


Jeff Nichols, Cisco Suresh Thoppay, NetApp Dre Jackson, NetApp

[role="lead"]
Dieses Dokument enthält die Architektur und das Design einer Virtual Desktop Infrastructure für bis zu 6000 Endbenutzer-Computing. Die Lösung ist auf Cisco UCS B200 M5 Blade-Servern der fünften Generation virtualisiert und startet VMware vSphere 7.01 Update 1 über FC SAN vom AFF A400 Storage-Array. Die virtuellen Desktops werden mit Citrix Provisioning Server 1912 LTSR und Citrix RDS/Citrix Virtual Apps & Desktops 1912 LTSR mit einer Kombination aus RDS-gehosteten Shared-Desktops (6000), zusammengefassten und/oder nicht-persistenten gehosteten virtuellen Windows 10-Desktops (5000) bereitgestellt. Und persistente gehostete virtuelle Windows 10-Desktops, die mit Citrix Machine Creation Services (5000) bereitgestellt werden, um die Benutzerzahl zu unterstützen. Gegebenenfalls enthält das Dokument Best Practice-Empfehlungen und Hinweise zur Dimensionierung für die Implementierung dieser Lösung bei Kunden.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/cisco_ucs_ctx1912esxi7u1_flexpodV2.html["FlexPod-Datacenter mit virtuellen Citrix Apps  Desktops 1912 LTSR und VMware vSphere 7 für bis zu 6000 Arbeitsplätze"^]
