---
sidebar: sidebar 
permalink: security/flexpod-fips-introduction.html 
keywords: tr4892, 4892introduction, hitech, fips, hit, ephi, 
summary: 'Dieses Dokument bietet eine technische Übersicht zu einem Cisco Unified Computing System (Cisco UCS), Cisco Nexus, Cisco MDS und einer auf NetApp ONTAP basierenden FlexPod Infrastruktur zum Hosten von IT-Applikationen oder Lösungen im Gesundheitswesen, die FIPS 140-2 Sicherheit erfordern.' 
---
= TR-4892: FIPS 140-2 Security-konforme FlexPod Lösung für das Gesundheitswesen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


JayaKishore Esanakula, NetApp John McAbel, Cisco

Das Health Information Technology for Economic and Clinical Health Act (HITECH) erfordert die Federal Information Processing Standard (FIPS) 140-2-validierte Verschlüsselung elektronischer geschützter Gesundheitsdaten (ePHI). Anwendungen und Software FÜR den Bereich Health Information Technology (HITS) müssen mit FIPS 140-2 konform sein, um die Zertifizierung zum Promoting Interoperability Program (ehemals sinnvoller Einsatz des Incentive-Programms) zu erhalten. Teilnahmeberechtigte Anbieter und Krankenhäuser müssen einen FIPS 140-2 (Level 1)-konformen TREFFER für die Aufnahme von Incentives für Medicare und Medicaid sowie die Vermeidung von Kostenerstattungen durch das Center for Medicare and Medicaid (CMS) verwenden. Nach FIPS 140-2 zertifizierte Verschlüsselungsalgorithmen gelten als technische Sicherheitsmaßnahmen, die gemäß der erforderlich sind https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/index.html["Sicherheitsregel"^] Des Health Information Portability and Accountability Act (HIPAA).

FIPS 140-2 ist eine USA Dieser Standard erfüllt die Sicherheitsanforderungen für kryptografische Module in Hardware, Software und Firmware, die sensible Daten schützen. Die Einhaltung der Standards ist für die Verwendung durch die USA vorgeschrieben Regierungsbehörden und IT wird häufig auch in regulierten Branchen wie Finanzdienstleistungen und Gesundheitswesen eingesetzt. Dieser technische Bericht hilft dem Leser, den FIPS 140-2-Sicherheitsstandard auf hohem Niveau zu verstehen. Außerdem hilft es dem Publikum, verschiedene Bedrohungen zu verstehen, denen Organisationen im Gesundheitswesen gegenüberstehen. Außerdem hilft der technische Bericht einem zu verstehen, wie ein FIPS 140-2-konformes FlexPod System zum Schutz von Gesundheitsressourcen bei der Implementierung auf einer konvergenten FlexPod Infrastruktur beitragen kann.



== Umfang

Dieses Dokument bietet eine technische Übersicht zu einem Cisco Unified Computing System (Cisco UCS), Cisco Nexus, Cisco MDS und einer auf NetApp ONTAP basierenden FlexPod Infrastruktur zum Hosten von IT-Applikationen oder Lösungen im Gesundheitswesen, die FIPS 140-2 Sicherheit erfordern.



== Zielgruppe

Dieses Dokument richtet sich an technische Leiter im Gesundheitswesen sowie an Lösungstechniker von Cisco und NetApp Partnern und Professional Services-Mitarbeiter. NetApp geht davon aus, dass der Leser gute Kenntnisse der Konzepte zur Berechnung der Storage- und Computing-Größenbemessung sowie der technischen Vertrautheit mit Bedrohungen für das Gesundheitswesen, mit der Sicherheit im Gesundheitswesen, MIT IT-Systemen im Gesundheitswesen, mit Cisco UCS und NetApp Storage-Systemen hat.

link:flexpod-fips-cybersecurity-threats-in-healthcare.html["Die nächste: Cyber-Sicherheitsbedrohungen im Gesundheitswesen."]
