---
sidebar: sidebar 
permalink: security/security-ransomware_continue_business_operations_without_paying_ransom.html 
keywords: ransom, pay, business, operations, restore, data, attack, prevent, recover 
summary: Die in diesem Dokument beschriebenen NetApp Funktionen helfen Ihnen, Daten innerhalb weniger Minuten nach einem Angriff wiederherzustellen und Angriffe an erster Stelle zu vermeiden, sodass der Geschäftsbetrieb ungehindert weitergeführt werden kann. 
---
= Geschäftsbetrieb ohne Lösegeld fortsetzen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Die in diesem Dokument beschriebenen NetApp Funktionen helfen Ihnen, Daten innerhalb weniger Minuten nach einem Angriff wiederherzustellen und Angriffe an erster Stelle zu vermeiden, sodass der Geschäftsbetrieb ungehindert weitergeführt werden kann.

Sie können einen Zeitplan für Snapshot Kopien festlegen, um die gewünschte Recovery-Zeitvorgabe (Recovery Point Objective, RPO) zu erfüllen. Auf Snapshot Kopien basierende Wiederherstellungsvorgänge sind sehr schnell. Somit kann ein sehr geringes Recovery Time Objective (RTO) erreicht werden.

Vor allem müssen Sie kein Lösegeld als Folge eines Angriffs zahlen, und Sie können schnell wieder zu normalen Operationen.
