---
sidebar: sidebar 
permalink: healthcare/medical-imaging_additional_information.html 
keywords: additional, information, flexpod, medical, imaging 
summary: Sehen Sie sich die folgenden Dokumente und Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren. 
---
= Weitere Informationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Sehen Sie sich die folgenden Dokumente und Websites an, um mehr über die in diesem Dokument beschriebenen Daten zu erfahren:

* Design-Leitfaden: FlexPod Datacenter for AI/ML with Cisco UCS 480 ML for Deep Learning
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_c480m5l_aiml_design.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_c480m5l_aiml_design.html"^]

* FlexPod Datacenter-Infrastruktur mit VMware vSphere 6.7 U1, Cisco UCS der vierten Generation und NetApp AFF A-Series
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_vmware_netappaffa.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_vmware_netappaffa.html"^]

* FlexPod Datacenter Oracle Database Backup with SnapCenter – Lösungsüberblick
+
https://www.netapp.com/us/media/sb-3999.pdf["https://www.netapp.com/us/media/sb-3999.pdf"^]

* FlexPod Datacenter mit Oracle RAC Datenbanken auf Cisco UCS und NetApp AFF A-Series
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orc12cr2_affaseries.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orc12cr2_affaseries.html"^]

* FlexPod Datacenter mit Oracle RAC auf Oracle Linux
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orcrac_12c_bm.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orcrac_12c_bm.html"^]

* FlexPod für Microsoft SQL Server
+
https://flexpod.com/solutions/use-cases/microsoft-sql-server/["https://flexpod.com/solutions/use-cases/microsoft-sql-server/"^]

* FlexPod von Cisco und NetApp
+
https://flexpod.com/["https://flexpod.com/"^]

* https://fieldportal.netapp.com/content/734702["NetApp Lösungen für MongoDB"^] Lösungsüberblick (NetApp Login erforderlich)
+
https://fieldportal.netapp.com/content/734702["https://fieldportal.netapp.com/content/734702"^]

* TR-4700: SnapCenter Plug-in für Oracle Database
+
https://www.netapp.com/us/media/tr-4700.pdf["https://www.netapp.com/us/media/tr-4700.pdf"^]

* NetApp Produktdokumentation
+
https://www.netapp.com/us/documentation/index.aspx["https://www.netapp.com/us/documentation/index.aspx"^]

* Lösungen von FlexPod für Virtual Desktop Infrastructure (VDI)
+
https://flexpod.com/solutions/use-cases/virtual-desktop-infrastructure/["https://flexpod.com/solutions/use-cases/virtual-desktop-infrastructure/"^]


