---
sidebar: sidebar 
permalink: ent-db/fpd-sap-afa-design.html 
keywords: flexpod, cisco, sap, hana, ucs, aff, a-series, tdi 
summary: 'Dieses Dokument beschreibt die FlexPod Lösung von Cisco und NetApp, bei der es sich um einen validierten Ansatz für die Implementierung von SAP HANA Tailored Datacenter Integration (TDI) Umgebungen handelt.' 
---
= FlexPod Datacenter for SAP Solution with Cisco UCS Manager 4.0 and NetApp AFF A-Series – Design
:allow-uri-read: 


Pramod Ramamurthy, Cisco Marco Schoen, NetApp

Dieses Dokument beschreibt die FlexPod Lösung von Cisco und NetApp, bei der es sich um einen validierten Ansatz für die Implementierung von SAP HANA Tailored Datacenter Integration (TDI) Umgebungen handelt. Dieses validierte Design enthält Richtlinien und ein Framework zur Implementierung von SAP HANA mit Best Practices von Cisco und NetApp.

FlexPod ist eine führende integrierte Infrastruktur, die eine Vielzahl von Enterprise-Workloads und Anwendungsfällen unterstützt. Diese Lösung ermöglicht Ihnen die schnelle und zuverlässige Implementierung von SAP HANA mit einem Modell eines maßgeschneiderten Datacenter-Integrationsmodus.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_sap_netappaffa_design.html["FlexPod Datacenter for SAP Solution with Cisco UCS Manager 4.0 and NetApp AFF A-Series – Design"^]
