---
sidebar: sidebar 
permalink: ent-db/fpd-oracle-rac-db.html 
keywords: flexpod, datacenter, oracle, rac, cisco, ucs, aff, mds, deploy 
summary: Cisco Validated Designs umfassen Systeme und Lösungen, die entwickelt, getestet und dokumentiert wurden, um Kundenimplementierungen zu vereinfachen und zu verbessern. 
---
= FlexPod Datacenter mit Oracle RAC Datenbanken auf Cisco UCS und NetApp AFF A-Series
:allow-uri-read: 


Tushar Patel, Cisco Hardikkumar Vyas, Cisco

Cisco Validated Designs umfassen Systeme und Lösungen, die entwickelt, getestet und dokumentiert wurden, um Kundenimplementierungen zu vereinfachen und zu verbessern. Bei diesen Designs wird ein breites Spektrum an Technologien und Produkten in ein Portfolio von Lösungen integriert, das speziell für die Geschäftsanforderungen der Kunden entwickelt wurde. Gemeinsam entwickeln Cisco und NetApp FlexPod, das als Grundlage für eine Vielzahl an Workloads dient und effiziente Architekturdesigns ermöglicht, die auf den Kundenanforderungen basieren. Eine FlexPod Lösung ist ein validierter Ansatz für die Implementierung von Technologien von Cisco und NetApp als Shared Cloud-Infrastruktur.

Das FlexPod Datacenter mit NetApp All Flash AFF System ist eine konvergente Infrastrukturplattform, die erstklassige Technologien von Cisco und NetApp in einer leistungsstarken, konvergenten Plattform für Enterprise-Applikationen vereint. Cisco und NetApp arbeiten eng mit Oracle zusammen, um die anspruchsvollsten transaktionsorientierten und reaktionszeitabhängigen Datenbanken zu unterstützen, die moderne Unternehmen benötigen.

Dieses Cisco Validated Design (CVD) beschreibt die Referenzarchitektur von FlexPod Datacenter unter Verwendung von Cisco UCS und NetApp All Flash AFF Storage zur Implementierung einer hochverfügbaren Oracle RAC Datenbankumgebung. In diesem Dokument werden die Hardware- und Softwarekonfiguration der involvierten Komponenten sowie die Ergebnisse verschiedener Tests dargestellt. Dieses Dokument bietet darüber hinaus Implementierungs- und Best Practices-Anleitungen für Cisco UCS Compute Server, Cisco Fabric Interconnect Switches, Cisco MDS Switches, Cisco Nexus Switches, NetApp AFF Storage und Oracle RAC Datenbanken.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orc12cr2_affaseries.html["FlexPod Datacenter mit Oracle RAC Datenbanken auf Cisco UCS und NetApp AFF A-Series"^]
