---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_requirements.html 
keywords: netapp, ontap, cisco, intersight, hardware, software, licensing, requirements 
summary: Stellen Sie sicher, dass die Hardware-, Software- und Lizenzierungsanforderungen für die Integration von NetApp ONTAP Storage mit Cisco Intersight erfüllt werden. 
---
= Anforderungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Überprüfen Sie, ob Sie die Hardware-, Software- und Lizenzierungsanforderungen für die NetApp ONTAP-Storage-Integration mit Cisco Intersight erfüllen.



== Hardware- und Softwareanforderungen

Dies sind die Mindestanforderungen an Hardware und Software, die für die Implementierung der Lösung erforderlich sind. Je nach den Anforderungen des Kunden können die in einer konkreten Implementierung dieser Lösung verwendeten Komponenten variieren.

|===
| Komponente | Anforderungsdetails 


| NetApp ONTAP | ONTAP 9.7P1 und höher 


| NetApp Active IQ Unified Manager | Die neueste Version von NetApp Active IQ Unified Manager ist erforderlich (derzeit 9.14RC1). 


| NetApp Storage Array | Alle ONTAP ASA-, AFF- und FAS-Storage-Arrays werden für ONTAP 9.7P1 und höher unterstützt 


| Virtualisierungshypervisor | VSphere 7.0 und höher 
|===

NOTE: Siehe https://intersight.com/help/saas/supported_systems["Von Cisco Intersight unterstützte Systeme"^] Für die Mindestanforderungen von Cisco UCS Compute Komponenten und der UCSM Version



== Cisco Intersight Lizenzierungsanforderungen

Cisco Intersight bietet Services wie Infrastrukturservice und Cloud Orchestrator Service zum Managen, Automatisieren und Optimieren von physischem Storage (NetApp-Storage). Mit diesen Services können Sie Cisco UCS-Server und Cisco HyperFlex-System verwalten. Beim Infrastructure Service und Cloud Orchestrator Service kommt ein abonnementbasiertes Lizenzmodell mit mehreren Tiers zum Einsatz. Sie können die erforderliche Cisco UCS Server Volume-Tier für die ausgewählte Abonnementlaufzeit auswählen.

.Lizenzmodell
Das Lizenzmodell von Cisco Intersight Infrastructure Services wurde vereinfacht und bietet nun die folgenden zwei Ebenen:

* *Cisco Intersight Infrastructure Services Essentials* - die Lizenzstufe Essentials bietet Serververwaltung einschließlich globaler Statusüberwachungsfunktionen, Inventarisierung, proaktiven Support durch Cisco TAC-Integration, Multi-Faktor-Authentifizierung sowie SDK- und API-Zugriff.
* * Cisco Intersight Infrastructure Services Advantage* - die Advantage-Lizenz-Tier bietet fortschrittliches Servermanagement mit erweiterter Transparenz, Integration in die Systeme anderer Anbieter, Automatisierung von Hardware und Software von Cisco und Drittanbietern sowie Multi-Domain-Lösungen.


Weitere Informationen zu den Funktionen, die von verschiedenen Lizenzstufen abgedeckt werden, finden Sie unter https://intersight.com/help/saas/getting_started/licensing_requirements/lic_infra#licensing_model["Infrastructure Services Lizenz"^].
