---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_new.html 
keywords: 'netapp, cisco, ontap, intersight, flexpod, what"s new, features, release notes, enhancements' 
summary: Cisco Intersight stellt neue Versionen vor, die Ihnen neue Funktionen, Verbesserungen und Fehlerbehebungen bieten. 
---
= Was ist neu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
In diesem Abschnitt werden die neuen Funktionen aufgeführt, die für Cisco Intersight mit NetApp ONTAP Storage verfügbar sind.



== Januar 2024

* NetApp Storage-Orchestrierung mit Referenz-Workflows, die jetzt über die in GitHub zum Download zur Verfügung stehen https://github.com/ucs-compute-solutions/FlexPod-Intersight-Workflow["FlexPod Intersight Workflow-Repository"^]. Weitere Informationen zu den neuen Referenz-Workflows in GitHub finden Sie unter link:ci-qsg_use_cases.html["Anwendungsfall 2: NetApp Storage-Orchestrierung anhand von Referenz-Workflows"^].




== November 2023

* Die Seite NVMe-Namespaces im Abschnitt Inventar der Benutzeroberfläche wurde hinzugefügt.




== August 2023


NOTE: Ein Upgrade auf NetApp Active IQ Unified Manager 9.13GA ist erforderlich, um Kompatibilität und volle Funktionalität mit der aktuellen Version sicherzustellen.

* Verbesserung des Tasks Neue intelligente NetApp-LUN, um deutlich die Verfügbarkeit von Auswahloptionen für das Erstellen einer neuen Initiatorgruppe oder das Auswählen einer vorhandenen Initiatorgruppe anzuzeigen. Wenn Benutzer jetzt das Kontrollkästchen aktivieren, um eine neue Initiatorgruppe zu erstellen, ist der Parameter zur Auswahl einer vorhandenen Initiatorgruppe nicht mehr verfügbar. Wenn Benutzer das Kontrollkästchen deaktivieren, um eine neue Initiatorgruppe zu erstellen, wird der vorhandene Parameter für die Initiatorgruppe dann verfügbar.
* Erweitert die Aufgaben Neue NetApp-LUN-Zuordnung und NetApp-LUN-Zuordnung entfernen. Die neue Beziehung zwischen der LUN und der Initiatorgruppe wird jetzt aktualisiert. Die UI-Bestandsaufnahme wird bei der Ausführung der Aufgabe sofort sowohl für die LUN als auch für die Initiatorgruppe aktualisiert.
* Die Seite „Prüfungen“ wird jetzt ordnungsgemäß geladen, wenn sich die Benutzer zum ersten Mal anmelden, und es ist keine Aktualisierung mehr erforderlich.




== Juli 2023


NOTE: Ein Upgrade auf NetApp Active IQ Unified Manager 9.13GA ist erforderlich, um Kompatibilität und volle Funktionalität mit der aktuellen Version sicherzustellen.

* Aktualisierte Namen für NetApp-Storage-Aufgaben. Unter Use Case 3 Benutzerdefinierte Workflows mit Designer-freiem Formular finden Sie eine vollständige Liste der umbenannten Aufgaben.
* Die IP-Adresse der NFS-Schnittstelle wurde als Ausgabe des Tasks „Neues NetApp-NAS-Smart-Volume“ hinzugefügt.
* Der Registerkarte „Checks“ wurde eine Überprüfung hinzugefügt, ob es sich bei der ASUP Übertragung um eine HTTPS-Übertragung handelt.
* Der richtige Tier-Typ für alle Tiers wird nun ordnungsgemäß unter der Benutzeroberfläche „Tiers“ angezeigt.
* Alle kompatiblen Lizenzen werden jetzt ordnungsgemäß auf der Seite Lizenzen angezeigt.
* Der genaue Wert für CIFS-Freigaben ohne oder ohne Home-Verzeichnis wird jetzt auf der Seite Freigaben angezeigt.
* Sortierung und Filterung sind jetzt für die zugeordnete Spalte auf der SEITE LUNS aktiviert.
* Sortieren und Filtern aktiviert nun die Spalte Authentifizierung aktiviert auf der Seite NTP-Server.
* Neue Prüfungen und die folgenden entsprechenden Kategorien wurden der Registerkarte Prüfungen hinzugefügt.
+
** Sicherheit
** Anti-Ransomware
** Gesteigerte
** Andere


* In der Detailansicht „Bestand“ wird jetzt ein Bericht anstelle der physisch genutzten Kapazität verwendet.




== Juni 2023


NOTE: Ein Upgrade auf NetApp Active IQ Unified Manager 9.13RC1 ist erforderlich, um die Kompatibilität und vollständige Funktionalität der aktuellen Version sicherzustellen.

* Aktualisierte Namen für NetApp-Storage-Aufgaben. Siehe link:ci-qsg_use_cases.html["Anwendungsfall 3: Benutzerdefinierte Workflows mit Designer-freiem Formular"^] Für die vollständige Liste der umbenannten Aufgaben.




== April 2023

* Die Registerkarten Protection Policies (SnapMirror) und Snapshot Policies wurden im Abschnitt Inventar der Benutzeroberfläche auf der Seite Policies hinzugefügt.
* Die Seite NFS-Clients wurde im Abschnitt „Inventar“ der Benutzeroberfläche hinzugefügt.
* Geschützte Spalte auf der Seite Speicher-VMs im Abschnitt Inventar der Benutzeroberfläche hinzugefügt.
* Geändert, wie Informationen zur Datenreduzierung gemeldet und angezeigt werden.
* Die Registerkarten „Lokale Ebene“ und „Cloud-Ebene“ wurden auf der Seite „Tiers“ im Abschnitt „Inventar“ der Benutzeroberfläche hinzugefügt.
* Die Spalte Knoten wird nun nach der Spalte Name auf der Seite Ports im Abschnitt Inventar der Benutzeroberfläche angezeigt.




== Januar 2023


NOTE: Ein Upgrade auf NetApp Active IQ Unified Manager 9.12 GA ist erforderlich, um Kompatibilität und vollständigen Funktionalität der aktuellen Version zu gewährleisten. Eine Liste bekannter Probleme in Bezug auf diese Version finden Sie unter <<Bekannte Probleme>>.

* Intersight Interoperabilitätsprüfungen können jetzt bei Kompatibilitätsprüfungen zwischen den Firmware-Modi UCSM und IMM unterscheiden.
* Schutzbeziehungen werden für ONTAP 9.7 nicht in Intersight angezeigt. Dieses Problem wurde in ONTAP 9.8RC1 behoben.




== August 2022


NOTE: Ein Upgrade auf NetApp Active IQ Unified Manager 9.11 GA ist erforderlich, um Kompatibilität und vollständigen Funktionalität der aktuellen Version zu gewährleisten. Eine Liste bekannter Probleme in Bezug auf diese Version finden Sie unter <<Bekannte Probleme>>.

* Aktualisierte Berechnung der verfügbaren Cluster-Kapazität, die dem System Manager entspricht
* Aktualisierte Cluster General Seite, um die Zusammenfassung der Performance-Metriken auszublenden, bis Performance-Daten gefüllt sind
* Problem mit der allgemeinen Cluster-Seite, das gelegentlich die Seite aufhängt, wurde behoben
* CIFS-Freigaben, CIFS-Services, qtrees und SVM SnapMirror-Richtlinien wurden zum Back-End-Inventar hinzugefügt.
* Freigaben und qtrees wurden im UI-Navigationsmenü unter dem Abschnitt „Logischer Bestand“ hinzugefügt
* Freigaben wurden als Registerkarte von einer ausgewählten Storage-VM hinzugefügt
* CIFS-Serviceinformationen auf der Registerkarte Speicher-VM Allgemein hinzugefügt, wenn die Speicher-VM CIFS aktiviert ist
* Es wurde eine Cluster-Scheckseite hinzugefügt, auf der Benutzer die Konfiguration von NetApp Storage-Systemen unter Einhaltung von Best Practices überprüfen können




== Juli 2022

* Verbesserte Grafikfunktionen für Cluster Data Reduction Ratio sind jetzt im Capacity Widget verfügbar
* Die Registerkarte FC-Schnittstellen wurde der Seite Netzwerkschnittstellen hinzugefügt
* Erstellen eines neuen Volumens mit der generischen "New Storage Volume" Aufgabe setzt nun Volumen-Raum-Garantie auf keine und Snapshot Reserve Prozent auf 0%
* Kommentarfeld unter der Task Snapshot-Richtlinie bearbeiten ist jetzt optional und muss nicht mehr zwingend angegeben werden
* Verbesserte Einheitlichkeit bei UI-Bestand und -Orchestrierung
* Die Kapazitätsinformationen von Intersight in der Clusterkapazität entsprechen jetzt der System Manager
* Kontrollkästchen unter Neue Aufgabe für virtuelle Speicher hinzugefügt, um alle Parameter beim Erstellen einer neuen Managementoberfläche anzuzeigen, um die Benutzerfreundlichkeit zu verbessern
* Protokolle unter Client Match verschoben, jetzt in Übereinstimmung mit System Manager
* Allgemeine Seite „Exportrichtlinie“ mit Zugriffsprotokoll(en)
* igroup Entfernung wird jetzt bedingt protokolliert
* „Failover Policy“ und „autorevert“ Parameter für NAS unter New Storage NAS Data Interface und New Storage iSCSI Data Interface hinzugefügt
* Rollback für New Storage NAS Smart Volume Task entfernt jetzt die Exportrichtlinie, wenn keine anderen Volumes verbunden sind
* Hat Verbesserungen für Smart Volume und Smart LUN-Aufgaben vorgenommen




== April 2022


NOTE: Um die Kompatibilität und vollständige Funktionalität zukünftiger Versionen sicherzustellen, wird ein Upgrade des NetApp Active IQ Unified Manager auf Version 9.10P1 empfohlen.

* Seite „Broadcast Domain to Ethernet Port Detail“ hinzugefügt
* Veränderte den Begriff „Aggregat“ zu „Tier“ für das Aggregat und SVM innerhalb der Benutzeroberfläche
* Änderung des Begriffs „Cluster Status“ in „Array Status“
* MTU-Filter funktioniert jetzt für <,>,=,<=,>= Zeichen
* Seite „Netzwerkschnittstelle“ wurde der Cluster-Bestandsaufnahme hinzugefügt
* AutoSupport zu Cluster Inventory hinzugefügt
* Hinzugefügt `cdpd.enable` Node-Option
* Objekt für CDP-Nachbar hinzugefügt
* NetApp Workflow-Storage-Aufgaben wurden innerhalb von Cisco Intersight hinzugefügt. Siehe link:ci-qsg_use_cases.html["Anwendungsfall 3: Benutzerdefinierte Workflows mit Designer-freiem Formular"^] Eine vollständige Liste aller NetApp Storage-Aufgaben.




== Januar 2022

* Es wurden ereignisbasierte Intersight-Alarme für NetApp Active IQ Unified Manager 9.10 oder höher hinzugefügt.



NOTE: Um die Kompatibilität und vollständige Funktionalität zukünftiger Versionen sicherzustellen, wird ein Upgrade des NetApp Active IQ Unified Manager auf Version 9.10 empfohlen.

* Legen Sie jedes Protokoll explizit für Storage Virtual Machine fest (wahr oder falsch)
* Zugewiesenes clusterHealthStatus Status ok-with-inused to OK
* Die Spalte „Systemzustand“ wurde auf der Seite „Cluster-Liste“ in die Spalte „Cluster Status“ umbenannt
* Zeigt das Speicher-Array „nicht erreichbar“ an, wenn das Cluster ausgefallen ist oder nicht erreichbar ist
* Die Spalte „Systemzustand“ wurde auf der Seite „Cluster General“ in die Spalte „Array Status“ umbenannt
* SVM hat jetzt eine Registerkarte „Volumes“, die alle Volumes für die SVM zeigt
* Das Volumen hat einen Abschnitt mit der Snapshot-Kapazität
* Lizenzen werden jetzt korrekt angezeigt




== Oktober 2021

* Aktualisierte Liste der NetApp Storage-Aufgaben, die innerhalb von Cisco Intersight verfügbar sind Siehe link:ci-qsg_use_cases.html["Anwendungsfall 3: Benutzerdefinierte Workflows mit Designer-freiem Formular"^] Eine vollständige Liste aller NetApp Storage-Aufgaben.
* „Systemzustand“ wurde auf der Seite „Cluster-Liste“ hinzugefügt.
* Erweiterte Details jetzt auf der Seite Allgemein für ein ausgewähltes Cluster verfügbar.
* Auf die NTP-Server-Tabelle kann jetzt über das Navigationsbereich zugegriffen werden.
* Neue Registerkarte „Sensoren“ mit der Seite „Allgemein“ für die Storage Virtual Machine hinzugefügt.
* VLAN und Link Aggregation Group Zusammenfassung jetzt verfügbar unter der Port General Seite.
* Spalte „Gesamtkapazität“, die in der Tabelle „Gesamtkapazität des Volumes“ hinzugefügt wurde
* Spalten zu Latenz, IOPS und Durchsatz, die unter Durchschnittliche Volume-Statistiken, Durchschnittliche LUN-Statistiken, Durchschnittliche Aggregatstatistiken, Durchschnittliche Storage VM-Statistiken und Durchschnittliche Node-Statistiken hinzugefügt werden
+

NOTE: Die oben genannten Performance-Kennzahlen stehen nur für Storage Arrays zur Verfügung, die über NetApp Active IQ Unified Manager 9.9 oder höher überwacht werden.





== Bekannte Probleme

* Wenn Sie eine AIQUM-Version 9.11 oder eine frühere Version verwenden, tritt eine Diskrepanz zwischen den angezeigten Werten auf der Seite „Speicherliste“ und dem Balken „Kapazität“ auf der Seite „Allgemein speichern“ auf. Um dieses Problem zu lösen, sollten Sie auf AIQUM 9.12 oder höher aktualisieren, um die Genauigkeit der angezeigten Kapazitätswerte zu gewährleisten.
* Wenn Sie AIQUM 9.11 oder eine frühere Version nutzen, können alle Überprüfungen, die auf der Registerkarte „Interoperabilität“ auf der Seite „integrierte Systeme“ durchgeführt werden, IMM und UCSM Cisco Komponenten nicht genau unterscheiden. Um dieses Problem zu beheben, sollten Sie auf AIQUM 9.12 aktualisieren, um sicherzustellen, dass alle Komponenten ordnungsgemäß identifiziert werden.
* Damit die Intersight-Speicherbestandsdaten während des Datenerfassungsprozesses nicht beeinflusst werden, müssen alle nicht unterstützten ONTAP-Cluster (z. B. Versionen unter ONTAP 9.7P1) aus dem Active IQ Unified Manager (AIQUM) entfernt werden.
* Für alle beanspruchten Ziele ist eine AIQUM-Version von 9.11 erforderlich, um eine erfolgreiche Durchführung von FlexPod Integrated System Interoperability Abfragen zu ermöglichen.
* Die Seite Speicherbestandsprüfungen wird nicht ausgefüllt, wenn der ONTAP-Cluster mit einem FQDN zu AIQUM hinzugefügt wird. Benutzer müssen AIQUM ONTAP-Cluster mithilfe einer IP-Adresse hinzufügen.

